export const nearbyAreas: Record<string, { name: string; slug: string }[]> = {
  solihull: [
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Redditch', slug: 'gutter-cleaning-redditch' },
    { name: 'Bromsgrove', slug: 'gutter-cleaning-bromsgrove' },
    { name: 'Coventry', slug: 'gutter-cleaning-coventry' },
    { name: 'Sutton Coldfield', slug: 'gutter-cleaning-sutton-coldfield' },
  ],
  wolverhampton: [
    { name: 'Walsall', slug: 'gutter-cleaning-walsall' },
    { name: 'Dudley', slug: 'gutter-cleaning-dudley' },
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Stourbridge', slug: 'gutter-cleaning-stourbridge' },
  ],
  walsall: [
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Wolverhampton', slug: 'gutter-cleaning-wolverhampton' },
    { name: 'Sutton Coldfield', slug: 'gutter-cleaning-sutton-coldfield' },
    { name: 'Sandwell', slug: 'gutter-cleaning-sandwell' },
  ],
  dudley: [
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'West Bromwich', slug: 'gutter-cleaning-west-bromwich' },
    { name: 'Wolverhampton', slug: 'gutter-cleaning-wolverhampton' },
    { name: 'Kidderminster', slug: 'gutter-cleaning-kidderminster' },
  ],
  'sutton-coldfield': [
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Walsall', slug: 'gutter-cleaning-walsall' },
    { name: 'Tamworth', slug: 'gutter-cleaning-tamworth' },
    { name: 'Solihull', slug: 'gutter-cleaning-solihull' },
  ],
  halesowen: [
    { name: 'Dudley', slug: 'gutter-cleaning-dudley' },
    { name: 'Stourbridge', slug: 'gutter-cleaning-stourbridge' },
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Smethwick', slug: 'gutter-cleaning-smethwick' },
  ],
  tamworth: [
    { name: 'Sutton Coldfield', slug: 'gutter-cleaning-sutton-coldfield' },
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Walsall', slug: 'gutter-cleaning-walsall' },
    { name: 'Coventry', slug: 'gutter-cleaning-coventry' },
  ],
  stourbridge: [
    { name: 'Dudley', slug: 'gutter-cleaning-dudley' },
    { name: 'Halesowen', slug: 'gutter-cleaning-halesowen' },
    { name: 'Kidderminster', slug: 'gutter-cleaning-kidderminster' },
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
  ],
  smethwick: [
    { name: 'Sandwell', slug: 'gutter-cleaning-sandwell' },
    { name: 'Oldbury', slug: 'gutter-cleaning-oldbury' },
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'West Bromwich', slug: 'gutter-cleaning-west-bromwich' },
  ],
  oldbury: [
    { name: 'Smethwick', slug: 'gutter-cleaning-smethwick' },
    { name: 'Sandwell', slug: 'gutter-cleaning-sandwell' },
    { name: 'Dudley', slug: 'gutter-cleaning-dudley' },
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
  ],
  'west-midlands': [
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Coventry', slug: 'gutter-cleaning-coventry' },
    { name: 'Wolverhampton', slug: 'gutter-cleaning-wolverhampton' },
    { name: 'Walsall', slug: 'gutter-cleaning-walsall' },
    { name: 'Dudley', slug: 'gutter-cleaning-dudley' },
    { name: 'Solihull', slug: 'gutter-cleaning-solihull' },
  ],
  'near-me': [
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Wolverhampton', slug: 'gutter-cleaning-wolverhampton' },
    { name: 'Coventry', slug: 'gutter-cleaning-coventry' },
    { name: 'Solihull', slug: 'gutter-cleaning-solihull' },
    { name: 'Walsall', slug: 'gutter-cleaning-walsall' },
    { name: 'Dudley', slug: 'gutter-cleaning-dudley' },
    { name: 'Sutton Coldfield', slug: 'gutter-cleaning-sutton-coldfield' },
    { name: 'Redditch', slug: 'gutter-cleaning-redditch' },
    { name: 'Worcester', slug: 'gutter-cleaning-worcester' },
    { name: 'Kidderminster', slug: 'gutter-cleaning-kidderminster' },
  ],
  birmingham: [
    { name: 'Sutton Coldfield', slug: 'gutter-cleaning-sutton-coldfield' },
    { name: 'Moseley', slug: 'gutter-cleaning-moseley' },
    { name: 'Kings Heath', slug: 'gutter-cleaning-kings-heath' },
    { name: 'Harborne', slug: 'gutter-cleaning-harborne' },
    { name: 'Erdington', slug: 'gutter-cleaning-erdington' },
    { name: 'Hall Green', slug: 'gutter-cleaning-hall-green' },
    { name: 'Northfield', slug: 'gutter-cleaning-northfield' },
    { name: 'Yardley', slug: 'gutter-cleaning-yardley' },
    { name: 'Small Heath', slug: 'gutter-cleaning-small-heath' },
    { name: 'Sparkhill', slug: 'gutter-cleaning-sparkhill' },
    { name: 'Perry Barr', slug: 'gutter-cleaning-perry-barr' },
    { name: 'Solihull', slug: 'gutter-cleaning-solihull' },
  ],
  coventry: [
    { name: 'Birmingham', slug: 'gutter-cleaning-birmingham' },
    { name: 'Solihull', slug: 'gutter-cleaning-solihull' },
    { name: 'Tile Hill', slug: 'gutter-cleaning-tile-hill' },
    { name: 'Binley', slug: 'gutter-cleaning-binley' },
  ],
};

