import { suburbPages } from '@/lib/suburbPageData';
import { CITY_GUTTER_LANDINGS } from '@/constants/cityGutterLandingData';
import { AREA_SLUGS } from '@/lib/areaSlugs';
import { CUSTOM_KEYWORD_CONTENT } from '@/lib/customKeywordData';

export interface KeywordPage {
  slug: string;
  titleTag: string;
  metaDescription: string;
  heroTitle: string;
  heroDescription: string;
  sections: {
    heading: string;
    content: string;
    bullets: string[];
  }[];
  cta: {
    title: string;
    description: string;
  };
  faqs?: {
    question: string;
    answer: string;
  }[];
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[,.'"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function titleCase(text: string): string {
  return text
    .split(/[\s-]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

const RAW_KEYWORDS = [
  "birmingham pressure washing",
  "checkatrade pressure washing",
  "cheapest window cleaner near me",
  "clean gutters price",
  "cleaning",
  "cleaning gutters",
  "conservatory roof clean",
  "corner gutter repair",
  "cost of gutter cleaning near me",
  "coventry window cleaners",
  "fascias and guttering near me",
  "flawless cleaning",
  "flawless cleaning services",
  "gutter",
  "gutter and fascia gutter cleaner, gutter cleaning bedworth, gutter cleaning service near me",
  "gutter cleaning systems",
  "gutter cleaning tools",
  "gutter prices",
  "gutter protection",
  "gutter repair near me",
  "guttering",
  "guttering and downpipe",
  "guttering and downpipe repairs",
  "guttering installation",
  "guttering moss protection",
  "guttering repairs",
  "guttering screwfix , gutters",
  "handyman services birmingham uk",
  "heavy duty guttering",
  "hire jetwash",
  "home gutter cleaning",
  "how much does it cost to clean your gutters",
  "how much does it cost to have gutters cleaned",
  "how much does it cost to replace gutters fascias and soffits",
  "how much gutter cleaning cost",
  "how much to clean gutters uk",
  "how much to clear guttering",
  "how much to have your gutters cleaned",
  "how much to replace guttering on terraced house",
  "how to clean gutters from the ground",
  "how to clean spouting",
  "how to clear guttering",
  "how to fix a leak in roof",
  "installing gutter guards",
  "installing guttering , leaking roof repair near me",
  "local gutter cleaning, local gutter cleaning service",
  "local window cleaners near me, plastic guttering",
  "pressure washing near me prices",
  "pressure washing service",
  "professional cleaning",
  "property maintenance companies birmingham",
  "wow roofing",
  "replace gutters",
  "replace section of gutter",
  "roof and gutter restoration",
  "roof cleaning near me",
  "roof moss removal near me",
  "roof replacement",
  "seamless guttering cost",
  "sky vac gutter cleaning",
  "smouts pressure washing",
  "soft washing near me , uk window cleaner",
  "vacuum gutter cleaning",
  "weatherfast gutters",
  "window cleaner near me",
  "window cleaner sutton coldfield",
  "window cleaner willenhall",
  "window cleaners birmingham",
  "window cleaners near me",
  "window cleaners nuneaton",
  "window cleaners sutton coldfield",
  "window cleaning birmingham",
  "window cleaning brierley hill",
  "window cleaning coventry",
  "gutter cleaning worcestershire",
  "gutter clearing birmingham",
  "gutter cleaners birmingham",
  "roof moss removal birmingham",
  "moss removal birmingham",
  "downpipe unblocking birmingham",
  "blocked gutter birmingham",
  "fascia and soffit cleaning birmingham",
  "commercial gutter cleaning west midlands",
  "gutter maintenance birmingham",
  "high level gutter cleaning",
  "same day gutter cleaning",
  "gutter cleaning no ladders",
  "best gutter cleaning birmingham",
  "how much does gutter cleaning cost uk",
  "gutter cleaning cost 3 bed semi",
  "gutter cleaning cost terraced house",
  "gutter cleaning cost detached house",
  "gutter cleaning cost bungalow",
  "average price for gutter cleaning birmingham",
  "how much to unblock a downpipe",
  "roof moss removal cost uk",
  "fascia cleaning cost",
  "commercial gutter cleaning prices",
  "gutter cleaning price per metre",
  "cheap gutter cleaning birmingham",
  "gutter cleaning quote online",
  "how much is gutter vacuum cleaning",
  "annual gutter cleaning plan cost",
  "why is my gutter overflowing",
  "water pouring over gutter when raining",
  "blocked downpipe symptoms",
  "gutter leaking at joint what to do",
  "damp patch on wall blocked gutter",
  "plants growing in gutter removal",
  "moss falling from roof into gutter",
  "birds nesting in gutter removal uk",
  "wasp nest in gutter who to call",
  "gutter overflowing behind fascia",
  "why does my gutter drip after rain",
  "sagging gutter causes",
  "gutter smells bad blocked",
  "green stains on wall from gutter",
  "water damage from blocked gutters insurance",
  "how often should gutters be cleaned UK",
  "best time of year to clean gutters",
  "how to tell if gutters need cleaning",
  "what happens if you never clean your gutters",
  "how do professionals clean gutters",
  "gutter vacuum vs ladder cleaning",
  "can you clean gutters from the ground",
  "how long does gutter cleaning take",
  "do I need scaffolding to clean gutters",
  "is gutter cleaning worth it",
  "gutter cleaning before winter checklist",
  "autumn leaves gutter maintenance",
  "how to prevent moss on roof",
  "does roof cleaning damage tiles",
  "soft washing vs pressure washing roof",
  "how often to remove moss from roof",
  "gutter guards worth it UK",
  "leaf guard installation pros and cons",
  "how to maintain gutters between cleans",
  "landlord responsibility gutter cleaning UK",
  "gutter cleaning 3 storey house",
  "gutter cleaning 4 storey building",
  "gutter cleaning flats and apartments",
  "gutter cleaning terraced house birmingham",
  "gutter cleaning victorian house",
  "gutter cleaning new build estate",
  "gutter cleaning above conservatory",
  "gutter cleaning dormer bungalow",
  "gutter cleaning HMO landlord",
  "block of flats gutter maintenance",
  "emergency gutter cleaning birmingham",
  "same day gutter unblocking",
  "gutter overflowing during storm help",
  "urgent downpipe unblocking near me",
  "weekend gutter cleaning birmingham",
  "gutter cleaning before selling house",
  "pre-winter gutter clear birmingham",
  "gutter cleaning after storm damage",
  "christmas gutter cleaning availability",
  "gutter frozen overflow ice winter",
  "fascia soffit cleaning near me",
  "conservatory roof cleaning birmingham",
  "solar panel bird proofing gutter",
  "driveway and gutter cleaning package",
  "render cleaning birmingham",
  "upvc cleaning birmingham",
  "gutter brightening service",
  "moss treatment biocide roof",
  "roof cleaning without pressure washer",
  "gutter deep clean service",
  "school gutter cleaning West Midlands",
  "office building gutter cleaning Birmingham",
  "warehouse gutter cleaning",
  "industrial gutter cleaning West Midlands",
  "retail park gutter maintenance",
  "church gutter cleaning Birmingham",
  "care home gutter cleaning",
  "property management gutter cleaning contracts",
  "landlord gutter cleaning service Birmingham",
  "commercial roof cleaning West Midlands",
  "gutter cleaning Sutton Coldfield Four Oaks",
  "gutter cleaning Marston Green",
  "gutter cleaning Pershore",
  "gutter cleaning Stourport-on-Severn",
  "gutter cleaning Bewdley",
  "gutter cleaning Alvechurch",
  "gutter cleaning Nuneaton",
  "gutter cleaning Kenilworth",
  "roof moss removal Sutton Coldfield",
  "gutter vacuum cleaning",
  "roof moss removal",
  "fascia soffit cleaning",
  "downpipe unblocking",
  "commercial gutter cleaning",
  "emergency gutter cleaning",
  "home guard plan",
  "commercial gutter cleaning Birmingham",
  "office gutter cleaning",
  "industrial gutter cleaning",
  "school gutter cleaning",
  "hospital gutter cleaning",
  "church gutter cleaning",
  "HMO gutter cleaning",
  "apartment block gutter cleaning",
  "block management gutter cleaning",
  "high rise gutter cleaning",
  "multi storey gutter cleaning",
  "gutter cleaning contract",
  "planned gutter maintenance",
  "gutter maintenance programme",
  "scheduled gutter cleaning",
  "annual gutter cleaning contract",
  "commercial downpipe cleaning",
  "commercial fascia and soffit cleaning",
  "industrial estate gutter cleaning",
  "business park gutter cleaning",
  "B2B gutter cleaning",
  "gutter cleaning tender",
  "gutter cleaning for letting agents",
  "managed property gutter cleaning",
  "commercial gutter cleaning services",
  "commercial property gutter maintenance",
  "gutter cleaning for facilities managers",
  "gutter cleaning portfolio properties",
  "gutter vacuum cleaning commercial",
  "gutter clearance commercial properties",
  "gutter cleaning quote commercial",
  "gutter cleaning for property developers",
  "new build gutter cleaning snagging",
  "commercial gutter cleaning cost",
  "commercial gutter cleaning price per property",
  "gutter cleaning for multiple sites",
  "approved gutter cleaning contractor",
  "gutter cleaning framework contractor",
  "gutter cleaning insurance compliance",
  "gutter cleaning duty of care landlord",
  "section 11 gutter cleaning obligations",
  "how often should commercial gutters be cleaned",
  "how much does commercial gutter cleaning cost UK",
  "what happens if gutters are not cleaned on commercial property",
  "commercial gutter cleaning near me",
  "gutter cleaning for schools Birmingham",
  "gutter cleaning for offices Birmingham",
  "gutter cleaning company for landlords Birmingham",
  "best commercial gutter cleaning company West Midlands",
  "gutter cleaning contractor for property management company",
  "who is responsible for gutter cleaning commercial tenancy",
  "gutter cleaning risk assessment method statement RAMS",
  "gutter cleaning without scaffolding commercial",
  "gutter vacuum system for tall buildings",
  "ground based gutter cleaning commercial 4 storey",
  "commercial gutter cleaning before and after",
  "commercial gutter cleaning health and safety",
  "commercial gutter cleaning insurance claim prevention",
  "do landlords have to clean gutters UK",
  "gutter maintenance obligations for landlords UK",
  "gutter cleaning service level agreement",
  "gutter cleaning for retail units Birmingham",
  "gutter cleaning for industrial units Wolverhampton",
  "gutter cleaning quote for multiple properties",
  "annual gutter maintenance plan for landlords",
  "gutter cleaning contract renewal reminder",
  "commercial gutter cleaning Solihull",
  "commercial gutter cleaning Sutton Coldfield",
  "commercial gutter cleaning Dudley",
  "commercial gutter cleaning Walsall",
  "commercial gutter cleaning Wolverhampton",
  "commercial gutter cleaning West Bromwich",
  "gutter cleaning facilities management company Birmingham",
  "gutter cleaning managing agent Birmingham",
  "gutter cleaning contractor CHAS accredited",
  "gutter cleaning contractor SafeContractor approved",
  "gutter cleaning contractor for schools procurement",
  "gutter cleaning NHS trust property",
  "gutter cleaning council owned buildings",
  "gutter cleaning housing association properties",
  "gutter overflow damage commercial property",
  "water damage commercial building blocked gutters",
  "gutter cleaning invoice for business",
  "gutter cleaning company that invoices monthly",
  "recurring gutter cleaning service business",
  "gutter cleaning company with public liability insurance",
  "gutter cleaning contractor Birmingham with references",
  "commercial gutter cleaning case study Birmingham",
  "retail gutter cleaning",
  "landlord gutter cleaning",
  "letting agent gutter cleaning",
  "property management gutter cleaning",
  "roof cleaning virginia water",
  "guttering cleaning kings norton",
  "guttering cleaning wythall",
  "local gutter cleaning",
  "blocked gutters",
  "roof cleaning sutton",
  "roof cleaning hampton",
  "industrial roof cleaning",
  "gutter installation birmingham",
  "roof washing",
  "how much to get gutters cleaned",
  "guttering system maintenance",
  "gutter survey",
  "gutter and downpipe cleaning near me",
  "gutter guards birmingham",
  "roof cleaning how wood",
  "gutter cleaning shepparton",
  "local fascias soffits guttering company birmingham",
  "same day gutter cleaning near me",
  "warehouse gutter repair near me",
  "local soffits company birmingham",
  "local fascias company birmingham",
  "rain gutter cleaning service",
  "moss removal cost",
  "gutter & fascia cleaning wolverhampton",
  "roof cleaning hatchford",
  "3 story house gutter cleaning",
  "free roof inspection",
  "vacuum gutter cleaning near me",
  "roof gutter cleaning near me",
  "local guttering specialists bromsgrove",
  "roof cleaning eastbury",
  "gutter roof cleaning",
  "gutter services worcester",
  "local guttering specialists redditch",
  "gutter cleaning kingstanding",
  "commercial gutter cleaning service near me",
  "guttering services south birmingham",
  "fascia cleaning prices",
  "moss removal from roof cost",
  "roof moss cleaning cost uk",
  "factory gutter cleaning",
  "blocked gutters and downpipes",
  "conservatory cleaning erdington",
  "conservatory roof cleaning dronfield",
  "how do you know if your gutters need cleaning",
  "industrial gutter cleaning near me",
  "gutter clearing",
  "gutter clearance",
  "gutter services",
  "gutter cleaning in my area",
  "gutters cleaning services",
  "guttering wolverhampton",
  "guttering worcester",
  "commercial roof cleaning services",
  "gutter clearance near me",
  "local gutter service",
  "gutter cleaning hampton",
  "guttering cleaning services",
  "guttering birmingham",
  "local gutter clearance",
  "guttering cleaning near me",
  "gutter repairs wolverhampton",
  "gutter cleaning near me uk",
  "guttering clearing",
  "gutter cleaning service near me",
  "gutter cleaning contractors",
  "gutter cleaning companies",
  "gutter repair and cleaning",
  "gutter cleaning uk",
  "gutters cleaning service",
  "gutter vacuum cleaning services",
  "commercial roof cleaners",
  "gutter cleaning wooton",
  "local gutter cleaning services",
  "guttering replacement birmingham",
  "gutters cleaning near me",
  "local gutter cleaning companies",
  "gutter and downpipe cleaning",
  "local gutter clearing",
  "gutter service",
  "new gutter worcester",
  "gutters cleaning",
  "gutter replacements birmingham",
  "gutter specialists",
  "guttering repairs worcester",
  "commercial gutter cleaning company",
  "gutter cleaning business",
  "guttering repairs near me worcester",
  "gutter unblocking services",
  "roof and guttering malvern",
  "get gutters cleaned",
  "gutter cleaning wootton",
  "commercial gutter cleaning companies",
  "guttering stoke on trent",
  "roof cleaning bell green",
  "rain gutter cleaning services",
  "gutters and guttering repairs worcester",
  "guttering cleaning henley-in-arden",
  "fascias stourbridge kingswinford",
  "gutter cleaning earley",
  "fascias",
  "wasp nest in gutter uk",
  "gutter cleaning lango",
  "roof and gutter inspection",
  "gutter cleaning contractor",
  "guttering cleaners",
  "professional gutter cleaning company",
  "gutter clearing service",
  "gutter cleaning ladwood",
  "gutters and guttering worcester",
  "guttering repairs wolverhampton",
  "free roof inspections",
  "gutter cleaning brierley",
  "domestic gutter cleaning",
  "gutter cleaning wolverhampton prices",
  "eavestrough cleaning services",
  "local gutter cleaning near me",
  "gutter cleaning for businesses",
  "gutter cleaning hednesford",
  "gutter cleaning clifton",
  "gutter moss removal",
  "roof and gutter contractors malvern",
  "wasp nest gutter",
  "guttering service birmingham",
  "guttering repair birmingham",
  "guttering cleaners near me",
  "upvc gutters windermere",
  "soffit and fascia cleaning in halesowen",
  "gutter washing",
  "gutter vacuum service",
  "guttering services stoke on trent",
  "gutter cleaned",
  "gutter cleaning tetbury",
  "gutter cleaning rowley",
  "clean gutters birmingham",
  "gutter cleaning great malvern",
  "professional gutter cleaning services",
  "best company to clean gutters",
  "my gutter ltd",
  "gutter cleaning & repair",
  "gutter cleaning companies near me",
  "gutter cleaning burntwood",
  "leak detection pelsall",
  "guttering specialists stoke on trent",
  "leak detection meriden",
  "gutters stoke-on-trent",
  "gutters blackwood",
  "gully cleaning near me",
  "wasps nest in gutter",
  "cladding cleaning bell green",
  "gutter replacement near me",
  "does gutter sealant go hard",
  "emergency gutter cleaning near me",
  "cleaner gutters",
  "gutter installation worcester",
  "worcester guttering",
  "local guttering specialists worcester",
  "roof inspections birmingham",
  "gutter cleaning and repairs",
  "gutter cleaning latham",
  "gutter cleaning westminster",
  "gutter vacuuming services",
  "industrial gutter cleaning services",
  "guttering and guttering repairs in worcester",
  "gutter cleaning leek",
  "leak detection chelmsley wood",
  "gutter clearing and cleaning",
  "fixing gutters",
  "high converting gutter cleaning websites",
  "office site tree cutting service west heath",
  "gutter cleaning southall",
  "office site tree cutting services west heath",
  "guttering installers wanstead",
  "leak detection tidbury green",
  "shared guttering law semi detached",
  "rain gutters near me",
  "gutters cleaning services near me",
  "local gutter cleaners near me",
  "rain gutter cleaning near me",
  "clean and repair gutters near me",
  "best gutter cleaning services",
  "gutter cleaning and replacement",
  "roof cleaning saughall",
  "upvc guttering in wednesbury",
  "local gutter cleaners",
  "gutter cleaning battle",
  "gutter clean near me",
  "guttering kidderminster",
  "render cleaning barr hall",
  "clean gutter service",
  "gutter clean repair",
  "uk gutter cleaning service",
  "roof cleaning barr hall",
  "leak detection tile hill",
  "gutter cleaning company near me",
  "gutter guards in sutton coldfield",
  "fascias sedgley",
  "gutter cleaning redbridge",
  "industrial gutter repair birmingham",
  "shopping centre gutter repair",
  "gutter cleaning business uk",
  "commercial gutter clearance",
  "professional gutter cleaning",
  "free annual roof inspection",
  "gutter cleaning experts",
  "commercial guttering cleaning",
  "guttering replacements solihull",
  "guttering and drainage in sutton coldfield",
  "gutter cleaning website",
  "gutter cleaning ash",
  "roof cleaner birmingham",
  "gutter cleaning cliffe",
  "guttering installations redditch",
  "gutter cleaning price list uk",
  "rainwater goods halesowen",
  "roof leaks shirley",
  "industrial and commercial gutter cleaning",
  "residential gutter cleaning service",
  "industrial roof cleaning services",
  "blocked gutter downpipe",
  "gutters cleaned",
  "guttering stoke congleton",
  "gutter cleaning queens park",
  "gutter cleaning atherton",
  "free guttering",
  "gutter pro near me",
  "gutter repairs quinton",
  "gutter cleaning dudley prices",
  "gutter cleaning near me within 5 mi",
  "gutter cleaning price list near me",
  "wasps in gutter",
  "new guttering near me",
  "wasps in gutter guards",
  "gutter cleaning and repair services",
  "gutters basin city",
  "hornet nest in gutter",
  "my gutter limited",
  "retail park gutter repair",
  "gutter cleaner near me",
  "guttering specialists near me",
  "window cleaner and gutter cleaning near me",
  "gutter flushers",
  "gutter guards in wolverhampton",
  "guttering installers near me",
  "standing water gutter repair",
  "gutters cleaners near me",
  "handyman gutter repair near me",
  "clean gutters near me",
  "gutter guards in cannock",
  "roof cleaning row heath",
  "gutter cleaning pendleton",
  "wolverhampton gutter repairs",
  "companies that clean gutters",
  "wolverhampton gutter repair",
  "rain gutter cleaning and repair",
  "gutter replacement worcester",
  "roof cleaning rowly",
  "gutter cleaning hoo",
  "gutter cleaning welling",
  "upvc guttering in cannock",
  "gutter cleaning west ham",
  "moss in gutters",
  "commercial gutter services",
  "drainpipe repairs cannock",
  "exterior cleaning chinbrook",
  "gutter cleaning march",
  "roof gutter cleaning service",
  "guttering and drainage in wednesbury",
  "gutters cleaners",
  "gutter cleaning tilehurst",
  "roof cleaning langham moor",
  "gutter cleaning angus",
  "gutter clean and repair",
  "gutter cleaning services coventry",
  "gutter cleaning commercial buildings",
  "commercial gutter clearing",
  "roof cleaning middle park",
  "roof cleaning worcester park",
  "retail gutter repair",
  "roof cleaning wooden fender",
  "gutter cleaning cleaning",
  "gutter specialist",
  "gutter cleaning scarisbrick",
  "commercial roof cleaning company",
  "gutter cleaning hayes",
  "gutter cleaning mirfield",
  "industrial unit gutter cleaning",
  "new guttering installations worcester",
  "roof cleaning penrith",
  "gutter cleaning rugeley",
  "commercial gutter cleaning and repair",
  "exterior cleaning birmingham",
  "tree inspection tipton",
  "gutter cleaning lordswood",
  "industrial gutter cleaners",
  "gutter cleaning cost",
  "gutter cleaning charlton",
  "gutter cleaning in stoke on trent",
  "render cleaning warley",
  "render cleaning elmdon",
  "leak detection wylde green",
  "gutter cleaning kingsley",
  "engineering company perry common",
  "roof cleaning hough",
  "roof cleaning langley upper green",
  "exterior cleaning fox street",
  "downpipe cleaning near me",
  "driveway and patio cleaning hollywood",
  "es un pareado",
  "gutter experts",
  "best gutter repairs near me",
  "semi detached",
  "wow window cleaning",
  "bromford",
  "downpipe blockage",
  "gutter cleaner",
  "worcester gutter cleaning",
  "cheap gutter cleaning near me prices",
  "how to clean gutters without a ladder uk",
  "wasps in gutters",
  "gutter clean and repair near me",
  "gutter cleaning and roof inspection",
  "gutter companies near me within 20 mi",
  "gutter fast",
  "gutter repairs northfield",
  "house gutters near me",
  "separating shared guttering",
  "average cost of roof and gutter cleaning",
  "gutter cleaning coventry prices",
  "gutter repairs harborne",
  "local gutter repairs",
  "roofing company alum rock",
  "rooftop gutter cleaning company",
  "07421 area code uk",
  "do wasps make nests in gutters",
  "gutter cleaning in my area near me",
  "gutter cleaning prices birmingham",
  "gutter repair cleaning near me",
  "local gutter cleaning services near me",
  "local gutter repair",
  "birmingham gutter repair",
  "gutter cleaning and fixing near me",
  "gutter pro lichfield",
  "guttering cleaning and repair near me",
  "local gutter cleaning service",
  "moss control west midlands",
  "why do gutter repairs fail repeatedly",
  "cheap gutter cleaning near me",
  "chelmsley wood",
  "cleaning gutters company",
  "free guttering near me",
  "gutter cleaning service near me prices",
  "guttering and fascia cleaning near me",
  "local guttering",
  "window and gutter cleaning",
  "gutter and fascia cleaning",
  "gutter cleaners and repair",
  "guttering cleveden",
  "guttering company near me",
  "guttering repair near me",
  "guttering specialist birmingham",
  "roof gutters cleaning",
  "upvc guttering in sutton coldfield",
  "aged care gutter cleaning",
  "commercial gutter cleaning service",
  "gutter cleaning and maintenance",
  "gutter cleaning and repair service",
  "gutter cleaning quote",
  "gutter repair services",
  "public sector gutter repair",
  "gutter clean mount lehman",
  "gutter cleaner company",
  "gutter cleaning regis",
  "local guttering companies near me",
  "gutter cleaner service near me",
  "uncluttered gutters",
  "gutter guards in wednesbury",
  "exterior cleaning row heath",
  "gutter cleaner waterfoot",
  "shopping centre gutter cleaning",
  "guttering services",
  "gutter work",
  "guttering broadway",
  "professional gutter repair service",
  "gutter clean abbotsford",
  "gutter repairs bromsgrove",
  "gutter cleaning virginia waters",
  "clean gutters service",
  "gutter clearrance",
  "leak detection bartley green",
  "gutter clearing services",
  "gutter leaks in hampton hill",
  "gutter maintenance",
  "gutter repairs halesowen",
  "upvc gutters fitted in blackwood",
  "gutter cleaning clapton",
  "guttering and drainage in wolverhampton",
  "leak detection rushall",
  "rosewood gutters",
  "pp gutters",
  "gutter repairs",
  "guttering materials in cannock",
  "guttering and drainage in cannock",
  "guttering materials in sutton coldfield",
  "guttering repairs near me",
  "guttering companies",
  "gutter cleaning specialists",
  "guttering installations worcester",
  "gutter repairs worcester park",
  "construction and roofers waste wordsley",
  "moss in gutter",
  "exterior cleaning bell green",
  "is spray gutter repair effective",
  "need my gutters cleaned",
  "premier gutter cleaning",
  "gutter repair stoke on trent",
  "i need my gutters cleaned",
  "factory gutter cleaning contractors",
  "gutter cleanout maple ridge",
  "window cleaning dickens heath",
  "roof cleaning blackheath royal standard",
  "roof health check",
  "clean roof and gutters",
  "gutter cleaning catliffe",
  "gutter repair without replacement",
  "gutter cleaning sale",
  "gutter cleaning sherwood park",
  "how long does spray gutter repair last commercial",
  "gutter cleaning stoke on trent",
  "cladding cleaning west midlands",
  "how long does spray gutter repair last",
  "driveway cleaning shirley",
  "gutter blocked",
  "why hidden gutters pose a risk to high-rise buildings",
  "gutter cleaning bow",
  "roof cleaning castle end",
  "leak detection cranmore",
  "gutter cleaning kingsbury",
  "burst pipe hayes",
  "roof cleaning blackwall",
  "gutter cleaning commercial",
  "roof cleaning deal hall",
  "retail roof cleaning",
  "brickwork cleaning shirley",
  "cleaners in birmingham uk",
];

function buildBullets(slug: string): string[] {
  const generic = [
    'Professional service across Birmingham and the West Midlands',
    'Fully insured with £10 million public liability cover',
    'Before and after photos on every job',
    'Free, no-obligation quotes in 60 seconds',
    'Same-day and next-day appointments where available',
    'Trusted local team with years of experience',
  ];

  if (slug.includes('pressure-washing') || slug.includes('jetwash') || slug.includes('driveway') || slug.includes('patio')) {
    return [
      'Professional pressure washing for driveways, patios, paths, and walls',
      'Commercial-grade hot water pressure washing equipment',
      'Removes algae, moss, oil stains, and ingrained dirt',
      'Safe for block paving, concrete, tarmac, and stone surfaces',
      'Fully insured with £10 million public liability cover',
      'Free quotes and same-day service across Birmingham',
    ];
  }

  if (slug.includes('window-clean')) {
    return [
      'Professional window cleaning using purified water systems',
      'Streak-free finish on all glass and frame surfaces',
      'Interior and exterior window cleaning available',
      'Hot purified water system for stubborn dirt and grime',
      'Fascias, soffits, and conservatories cleaned on request',
      'Regular schedules available — weekly, fortnightly, monthly',
    ];
  }

  if (slug.includes('gutter') || slug.includes('guttering')) {
    return [
      'Full gutter cleaning, repairs, and installation services',
      'Ground-level vacuum system — no ladders against your walls',
      'Downpipe testing and outlet clearing included',
      'Before and after photos sent with every visit',
      'Gutter repairs, brackets, and joint replacements',
      'Free quotes with no obligation to proceed',
    ];
  }

  if (slug.includes('roof-clean') || slug.includes('roof-moss') || slug.includes('roof-replacement') || slug.includes('roof-and-gutter')) {
    return [
      'Professional roof cleaning and moss removal services',
      'Low-pressure soft wash methods — safe for all tile types',
      'Biocide treatment to slow moss and algae regrowth',
      'Roof inspections and condition reports',
      'Gutter cleaning combined with roof work for full roofline care',
      'Fully insured with £10 million public liability cover',
    ];
  }

  return generic;
}

function generateSmartContent(keyword: string, slug: string): { heroTitle: string; heroDescription: string; sections: { heading: string; content: string; bullets: string[] }[]; faqs: { question: string; answer: string }[] } {
  const title = titleCase(keyword.replace(/[,.'"]/g, ' ').replace(/\s+/g, ' ').trim());

  // 1. WASPS / PEST NESTS IN GUTTERS
  if (slug.includes('wasp') || slug.includes('hornet') || slug.includes('nest')) {
    return {
      heroTitle: title,
      heroDescription: `Specialist removal of wasp nests, debris, and blockages from gutters and rooflines across Birmingham and the West Midlands. WOW Gutters Ltd safely clears nests and restores full rainwater flow. Call 07421 433910.`,
      sections: [
        {
          heading: `Safe Clearing of Wasps and Nests in Gutters`,
          content: `Wasps and hornets frequently choose the sheltered underside of roof tiles, fascia overhangs, and dry, debris-filled gutter troughs to build their nests. When a nest expands inside a gutter or leaf guard, it causes severe drainage blockages, trapping standing water and rotting fascias. WOW Gutters Ltd uses ground-level vacuum systems and long-reach equipment to safely extract nest remnants, mud structures, and compacted debris without damaging your guttering or roofline.`,
          bullets: [
            'Safe extraction of inactive wasp, hornet, and bird nests from gutters',
            'Clearing compacted mud, comb material, and organic debris from channel floors',
            'Unblocking downpipes and outlets obstructed by nest debris',
            'Ground-level high-reach vacuum system — safe, ladder-free operation',
            'Thorough water flow testing to verify free rainwater evacuation',
            'Full photographic confirmation before and after clearing',
          ],
        },
        {
          heading: `Why Wasps Target Gutters and How to Prevent Them`,
          content: `Gutters accumulated with autumn leaves and standing sludge create ideal moist nesting spots for insects during spring and summer. Once a nest blocks the channel, subsequent rain causes water to overflow behind the fascia board into roof voids. Regular annual vacuum clearing removes the nesting matter and eliminates standing water, stopping wasps from returning.`,
          bullets: [
            'Eliminates standing water and organic matter that attract nesting insects',
            'Prevents overflow water from penetrating fascia boards and cavity walls',
            'Mesh leaf guard inspection and cleaning where wasps have nested beneath guards',
            'Inspection of joints and seals for damage caused by trapped moisture',
            'Fully insured with £10 million public liability coverage',
            'Same-week appointments available across Birmingham and the West Midlands',
          ],
        },
      ],
      faqs: [
        {
          question: 'Do wasps build nests inside gutters and leaf guards?',
          answer: 'Yes. Wasps frequently build nests in dry leaf accumulations inside gutters or beneath mesh gutter guards where they are sheltered from wind and rain. Over time, the nest blocks water flow and causes chronic overflows.',
        },
        {
          question: 'How do you safely clear a wasp nest from gutters?',
          answer: 'We use industrial-strength ground-level vacuum systems with high-reach carbon fiber poles to extract the nest structure and surrounding silt completely to the channel floor without disturbing roof tiles.',
        },
        {
          question: 'Will clearing my gutters prevent wasps from nesting again?',
          answer: 'Yes. Keeping gutters clean and free of stagnant sludge and leaf litter removes the primary shelter and moisture sources that attract nesting wasps in late spring and summer.',
        },
        {
          question: 'How much does it cost to clear nest blockages from gutters?',
          answer: 'Standard residential gutter clearing with nest extraction starts from £50 to £120 depending on property size and roof height. We provide fixed upfront quotes before commencing work.',
        },
      ],
    };
  }

  // 2. SHARED GUTTERING & SEMI-DETACHED LAWS
  if (slug.includes('shared-gutter') || slug.includes('separating-shared') || slug.includes('semi-detached') || slug.includes('pareado')) {
    return {
      heroTitle: title,
      heroDescription: `Specialist shared guttering maintenance, repair, and boundary separation for semi-detached and terraced homes across Birmingham and the West Midlands. Expert advice and installation. Call 07421 433910.`,
      sections: [
        {
          heading: `Understanding Shared Guttering on Semi-Detached Homes`,
          content: `On UK semi-detached and terraced properties, gutters are often built as a single continuous trough across the party wall boundary with a shared downpipe. If one neighbour neglects gutter maintenance or has a dropped bracket, water backs up and overflows onto both properties. WOW Gutters Ltd provides comprehensive joint maintenance, boundary assessment, and specialist installation of separation joints and stop-ends so your half functions independently.`,
          bullets: [
            'Expert inspection of shared gutter runs and boundary downpipe configurations',
            'Installation of union separation joints and internal stop-ends at party walls',
            'Dedicated downpipe retrofitting to give your property independent drainage',
            'High-reach vacuum clearing of both halves with neighbour group discounts',
            'Camera surveys to document boundary joint condition for landlord/homeowner clarity',
            'Clear fixed pricing with £10m public liability insurance',
          ],
        },
        {
          heading: `UK Law and Best Practice for Shared Gutter Maintenance`,
          content: `Under UK property law, shared guttering is typically a mutual responsibility. Neither party may cause damage to the neighbour\'s side through neglect. The most effective long-term solution is either booking coordinated maintenance together (taking advantage of our multi-property discount) or installing a boundary divider with a dedicated downpipe so each homeowner controls their own drainage.`,
          bullets: [
            'Prevents water ingress caused by neighbour\'s blocked or leaking gutter section',
            'Eliminates boundary disputes through clear photographic condition reports',
            'Group discounts available when neighbouring properties are cleared together',
            'Quality uPVC fittings matched to existing gutter profiles (square, half-round, deep-flow)',
            'Ground-based vacuum cleaning — no damage to shared boundary walls or fascias',
            'Fast response across Birmingham, Solihull, Sutton Coldfield, and the West Midlands',
          ],
        },
      ],
      faqs: [
        {
          question: 'Who is legally responsible for shared gutters on a semi-detached house?',
          answer: 'Generally, both homeowners share responsibility for maintaining continuous gutter runs that cross the property boundary. If a blockage on one side causes damp damage to the other, the negligent party may be held liable.',
        },
        {
          question: 'Can you separate shared gutters so my drainage is independent?',
          answer: 'Yes. We can install an internal stop-end or union joint at the boundary line and fit an independent outlet and downpipe to ensure your rainwater discharges exclusively through your own drain.',
        },
        {
          question: 'Do you offer discounts if both neighbours book together?',
          answer: 'Yes. Our neighbourhood group discount offers up to 20% off when adjoining semi-detached or terraced properties are cleaned or serviced during the same visit.',
        },
        {
          question: 'How do you clean gutters without upsetting the neighbour?',
          answer: 'Our ground-based vacuum system operates safely from ground level without ladders touching either property\'s walls, providing before-and-after photographs for complete transparency.',
        },
      ],
    };
  }

  // 3. COMMERCIAL & INDUSTRIAL GUTTER / ROOF CLEANING
  if (slug.includes('industrial') || slug.includes('commercial') || slug.includes('warehouse') || slug.includes('factory') || slug.includes('retail') || slug.includes('shopping-centre') || slug.includes('business')) {
    const isRoof = slug.includes('roof');
    const serviceName = isRoof ? 'Commercial Roof Cleaning' : 'Commercial Gutter Cleaning';
    return {
      heroTitle: title,
      heroDescription: `Professional ${serviceName.toLowerCase()} and planned maintenance for industrial units, warehouses, retail parks, and commercial properties across Birmingham and the West Midlands. Fully insured (£10m) with RAMS. Call 07421 433910.`,
      sections: [
        {
          heading: `Specialist ${serviceName} for West Midlands Businesses`,
          content: `Industrial units, retail facilities, and commercial buildings feature high-capacity valley gutters, box troughs, and expansive roof surfaces that accumulate massive volumes of silt, moss, and windblown debris. Failure to maintain these systems leads to internal water damage, stock destruction, and insurance non-compliance. WOW Gutters Ltd provides industrial-grade vacuum extraction, high-pressure washing, and condition surveys tailored to commercial facilities.`,
          bullets: [
            'Industrial vacuum systems reaching up to 4 storeys from ground level',
            'High-capacity box gutter and valley gutter deep clearance',
            'Full downpipe flushing and siphon drainage system unblocking',
            'Out-of-hours, weekend, and shutdown scheduling for zero operational disruption',
            'Site-specific Risk Assessments and Method Statements (RAMS) provided as standard',
            'Detailed before, during, and after HD camera condition reports for compliance',
          ],
        },
        {
          heading: `Insurance Compliance and Preventative Maintenance Contracts`,
          content: `Commercial property leases and building insurance policies routinely require documented annual gutter and roof inspections. WOW Gutters Ltd offers scheduled maintenance contracts across Birmingham, Wolverhampton, Coventry, Dudley, and the Black Country, preventing emergency roof leaks and extending roofline asset life.`,
          bullets: [
            'Protects commercial assets, inventory, and electrical infrastructure from water ingress',
            'Prevents costly emergency callouts and structural roofline decay',
            'Compliant with Health and Safety Executive (HSE) working at height regulations',
            'Flexible invoicing and dedicated account management for facility managers',
            'Covering factories, distribution hubs, business parks, and public sector sites',
            'Fully insured with £10 million public liability and employer liability cover',
          ],
        },
      ],
      faqs: [
        {
          question: `How often should commercial ${isRoof ? 'roofs' : 'gutters'} be serviced?`,
          answer: 'Commercial properties should be cleared at least twice a year—late spring to clear seed pods and autumn to extract fallen leaves and roof moss before heavy winter rains.',
        },
        {
          question: 'Do you provide RAMS and health and safety documentation?',
          answer: 'Yes. We provide full site-specific Risk Assessments and Method Statements (RAMS), COSHH data sheets, and insurance certificates before any commercial work begins.',
        },
        {
          question: 'Can you work outside of our normal operating hours?',
          answer: 'Yes. We routinely schedule commercial and industrial cleans during early mornings, evenings, or weekends to prevent any disruption to your staff, customers, or logistics.',
        },
        {
          question: 'How do you access high-level commercial gutters safely?',
          answer: 'We utilize high-reach industrial vacuum systems from ground level up to 15 meters, combined with MEWPs (cherry pickers) and scaffold access where complex internal box gutters require hands-on maintenance.',
        },
      ],
    };
  }

  // 4. SPRAY REPAIRS & NON-REPLACEMENT GUTTER FIXES
  if (slug.includes('spray') || slug.includes('sealant') || slug.includes('standing-water') || slug.includes('without-replacement') || slug.includes('fail-repeatedly')) {
    return {
      heroTitle: title,
      heroDescription: `Expert evaluation of gutter spray repairs, standing water fixes, and long-lasting joint sealing across Birmingham and the West Midlands. WOW Gutters Ltd provides permanent repairs with full flow testing. Call 07421 433910.`,
      sections: [
        {
          heading: `Is Spray Gutter Repair Effective or Just a Temporary Patch?`,
          content: `Rubberized aerosol spray sealants are heavily marketed for quick DIY leak fixes, but in professional drainage applications, they routinely fail within 3 to 12 months. Standing water, thermal expansion, and UV radiation cause topical sprays to peel and crack. WOW Gutters Ltd provides genuine structural repairs—re-aligning dropped brackets, replacing perished rubber union gaskets, or installing continuous Plygene liners that solve leaks permanently without replacing the entire roofline.`,
          bullets: [
            'Honest assessment of whether a joint can be resealed or requires mechanical union replacement',
            'Fixing standing water pooling by resetting bracket gradients to the correct fall angle',
            'Industrial EPDM and silicone gasket replacements that accommodate thermal expansion',
            'Seamless gutter lining options for corroded cast iron, valley, or concrete gutters',
            'Full water flow testing following every repair to guarantee watertight performance',
            'Free photographic condition survey before and after every repair',
          ],
        },
        {
          heading: `Why Gutter Repairs Fail Repeatedly and How to Fix Them Permanently`,
          content: `Repairs fail repeatedly when the root cause—such as a dropped bracket creating a low point, or rotted timber behind the fascia—is ignored in favour of slapping sealant over a dirty seam. Our technicians thoroughly clean the channel floor to bare uPVC, inspect the fascia board, and install British Standard replacement parts designed to last for decades.`,
          bullets: [
            'Eliminates recurring leaks that cause stained external masonry and internal damp',
            'Restores optimal rainwater pitch so gutters drain completely with zero standing sludge',
            'Mobile service vans fully stocked with all standard uPVC, cast iron, and aluminium fittings',
            'Cost-effective alternative to complete gutter and roofline replacement',
            'Backed by written workmanship guarantees and £10m public liability insurance',
            'Same-week repair appointments across Birmingham, Solihull, and the West Midlands',
          ],
        },
      ],
      faqs: [
        {
          question: 'How long does spray gutter repair actually last?',
          answer: 'Topical aerosol sprays typically last 3 to 6 months before peeling under standing water and temperature swings. For long-term reliability, mechanical gasket replacement or seamless lining is required.',
        },
        {
          question: 'Can you fix standing water in gutters without replacing everything?',
          answer: 'Yes. Standing water is caused by improper fall angles. We re-align or replace the supporting brackets to restore the correct slope towards the downpipe outlet, allowing water to drain fully.',
        },
        {
          question: 'Does gutter sealant go hard over time?',
          answer: 'Low-grade mastics harden, turn brittle, and crack as gutters expand in summer heat. We use UV-stable, high-elasticity polymer sealants and genuine rubber union seals that flex with seasonal temperature changes.',
        },
        {
          question: 'How much does a professional gutter repair cost?',
          answer: 'Minor joint resealing and bracket repairs start from £45 to £95 when completed alongside a clean. We provide transparent, upfront fixed quotes before starting any work.',
        },
      ],
    };
  }

  // 5. LEAK DETECTION & DRAINAGE / BURST PIPES
  if (slug.includes('leak-detection') || slug.includes('burst-pipe') || slug.includes('drainpipe')) {
    return {
      heroTitle: title,
      heroDescription: `Specialist roofline leak detection and rainwater drainage diagnostics across Birmingham and the West Midlands. Pinpoint hidden gutter leaks, cracked downpipes, and water ingress. Call 07421 433910.`,
      sections: [
        {
          heading: `Precision Leak Detection for Rooflines and Rainwater Systems`,
          content: `Hidden leaks along rooflines, soffits, and rainwater downpipes are leading causes of severe interior damp, timber decay, and foundation erosion. Water often travels along rafters or behind cavity brickwork before manifesting as a damp ceiling patch far from the actual entry point. WOW Gutters Ltd uses wireless high-resolution camera probes, dye-testing, and pressure inspections to pinpoint exact failure points quickly.`,
          bullets: [
            'Non-invasive camera inspections of hidden valley gutters, box troughs, and roofline junctions',
            'Water flow and dye tracing to identify hairline fractures in concealed downpipes',
            'Inspection of fascia joints, soffit vents, and flashing seals for water ingress',
            'Pinpointing failed union seals, warped joints, and subterranean drainage blockages',
            'Immediate on-site repair capabilities from our fully stocked mobile vans',
            'Comprehensive photographic condition reports for homeowners and insurance claims',
          ],
        },
        {
          heading: `Why Early Leak Detection Saves Thousands in Repairs`,
          content: `Left unresolved, a minor gutter drip or fractured downpipe elbow can saturate exterior brickwork, cause toxic black mould indoors, and rot structural roof joists. Our rapid diagnostic service identifies the exact failure source and provides an immediate, guaranteed fix before structural damage spreads.`,
          bullets: [
            'Prevents expensive internal plaster damage, ceiling collapse, and timber dry rot',
            'Eliminates damp patches and salt efflorescence on exterior walls',
            'Transparent fixed-price diagnostics with no hidden callout charges',
            'Experienced drainage and roofline technicians with £10m public liability cover',
            'Serving all Birmingham postcodes, Solihull, Sutton Coldfield, and the West Midlands',
            'Same-day and emergency inspection slots available',
          ],
        },
      ],
      faqs: [
        {
          question: 'How do you find hidden leaks in gutters and downpipes?',
          answer: 'We combine real-time wireless camera probes inside high-level channels with controlled water flow testing to track moisture penetration directly to failed joints, cracked unions, or blocked outlets.',
        },
        {
          question: 'Can a leaking gutter cause damp inside my home?',
          answer: 'Yes. Constant rainwater overflow saturates exterior brickwork, penetrates cavity insulation, and causes damp patches, peeling wallpaper, and mould growth on interior upstairs walls.',
        },
        {
          question: 'Can you repair the leak immediately once detected?',
          answer: 'Yes. Our vans carry a comprehensive inventory of replacement unions, brackets, downpipes, and high-performance sealants, allowing us to fix most leaks during the same visit.',
        },
        {
          question: 'How much does roofline leak detection cost?',
          answer: 'Basic camera surveys and leak detection start from £40 to £75, with costs often integrated directly into the repair service. Call 07421 433910 for an instant quote.',
        },
      ],
    };
  }

  // 6. GULLY / DOWNPIPE BLOCKAGES & CLEANING
  if (slug.includes('downpipe') || slug.includes('gully') || slug.includes('blocked') || slug.includes('blockage') || slug.includes('flushers')) {
    return {
      heroTitle: title,
      heroDescription: `Professional downpipe unblocking, gully clearing, and gutter flow restoration across Birmingham and the West Midlands. WOW Gutters Ltd removes compacted blockages with flow testing. Call 07421 433910.`,
      sections: [
        {
          heading: `Complete Downpipe & Gully Clearance Services`,
          content: `When downpipes or ground gullies clog with compacted leaves, moss, and roof grit, entire gutter runs overflow within minutes of rainfall. Downpipe obstructions typically form at sharp swan-neck bends or bottom shoes where standard rods cannot reach. WOW Gutters Ltd employs high-pressure flushing nozzles, flexible mechanical rodding, and powerful vacuum suction to clear the entire rainwater run down to the underground soakaway or drain.`,
          bullets: [
            'Clearing stubborn downpipe blockages at swan-necks, elbows, and shoe fittings',
            'Ground-level rainwater gully silt extraction and leaf trap clearance',
            'High-pressure water flushing to ensure 100% unobstructed drainage flow',
            'Installation of balloon leaf guards and downpipe mesh strainers to prevent recurrence',
            'Camera verification to ensure no internal obstructions remain inside pipes',
            'Combined gutter vacuuming and downpipe service in a single visit',
          ],
        },
        {
          heading: `Signs Your Downpipe or Gully Is Blocked`,
          content: `Water pouring over gutter edges near downpipe outlets, gurgling sounds during rainfall, or water pooling around ground gullies are clear indicators of a restricted downpipe. Clearing the blockage promptly prevents cracked pipes in freezing winter weather and protects wall foundations.`,
          bullets: [
            'Eliminates foundation water pooling and brickwork saturation',
            'Prevents winter freeze-thaw damage that splits plastic and cast iron downpipes',
            'Ground-level operation — safe, fast, and completely mess-free',
            'Fixed upfront pricing with before-and-after photo documentation',
            'Fully insured local technicians covering all Birmingham and West Midlands areas',
            'Urgent same-day appointments available for severe rainwater overflows',
          ],
        },
      ],
      faqs: [
        {
          question: 'How do you clear a blocked downpipe without taking it apart?',
          answer: 'We use industrial vacuum suction from the top outlet combined with specialized high-pressure clearing nozzles that break up compacted plugs of silt and moss without dismantling pipework.',
        },
        {
          question: 'What causes downpipes to block repeatedly?',
          answer: 'Debris concentrates at swan-neck bends and elbow joints. If moss from the roof is not cleared or downpipe balloon guards are missing, fresh debris quickly forms another plug.',
        },
        {
          question: 'Is downpipe unblocking included in standard gutter cleaning?',
          answer: 'Yes. At WOW Gutters Ltd, outlet clearing and full downpipe flow testing are included as standard on every gutter cleaning visit.',
        },
        {
          question: 'How much does downpipe and gully clearance cost?',
          answer: 'Downpipe and gully unblocking typically costs between £40 and £80 depending on blockage severity, with fixed quotes provided before work starts.',
        },
      ],
    };
  }

  // 7. AREA-SPECIFIC GUTTERING & REPAIRS
  const areaMatch = slug.match(/(worcester|wolverhampton|stoke|malvern|redditch|bromsgrove|droitwich|solihull|sutton-coldfield|quinton|harborne|northfield|halesowen|cannock|coleshill|bell-green|kings-heath|edgbaston|erdington|kidderminster|tamworth|coventry|dudley|walsall|shirley|blackwood|pelsall|meriden)/i);
  if (areaMatch || slug.includes('guttering-') || slug.includes('gutters-') || slug.includes('gutter-repairs-')) {
    const areaName = areaMatch ? titleCase(areaMatch[1].replace(/-/g, ' ')) : 'the West Midlands';
    const isRepair = slug.includes('repair') || slug.includes('replacement') || slug.includes('install');

    return {
      heroTitle: title,
      heroDescription: `Professional ${isRepair ? 'gutter repairs, replacement and installation' : 'gutter cleaning and maintenance'} in ${areaName}. WOW Gutters Ltd provides ground-level vacuum clearing, camera surveys, and guaranteed workmanship. Call 07421 433910.`,
      sections: [
        {
          heading: `Trusted Gutter Services Across ${areaName}`,
          content: `WOW Gutters Ltd provides homeowners and businesses across ${areaName} with dependable, professional gutter maintenance. From traditional Victorian terraces and 1930s semi-detached homes to modern detached estates and commercial properties, our experienced local technicians keep your rainwater systems in peak condition.`,
          bullets: [
            `Complete gutter clearance and structural inspection across ${areaName}`,
            'Ground-level industrial vacuum system reaching up to 4 storeys without ladders',
            'Full downpipe flushing, outlet unblocking, and free-flow water testing',
            'Fixing leaking joints, union clips, sagging runs, and broken support brackets',
            'Before and after HD photographic proof provided with every visit',
            'Fully insured with £10 million public liability coverage',
          ],
        },
        {
          heading: `Why ${areaName} Properties Benefit From Regular Gutter Care`,
          content: `${areaName} experiences heavy seasonal rainfall and substantial tree cover, leading to rapid accumulation of autumn leaves, pine needles, and roof moss in gutter channels. Our comprehensive service extracts all debris to the channel floor, tests every downpipe, and ensures your property is 100% protected from water ingress.`,
          bullets: [
            'Protects brickwork, fascia timbers, and foundations from water damage and damp',
            'Fixed upfront pricing with no hidden charges or travel fees',
            'Same-week appointments and rapid response across all local postcodes',
            'Quality British Standard uPVC and cast iron replacement components',
            'Combined roof moss removal, fascia cleaning, and gutter packages available',
            'Highly rated by local customers across Google and Checkatrade',
          ],
        },
      ],
      faqs: [
        {
          question: `Do you provide gutter services in ${areaName}?`,
          answer: `Yes. WOW Gutters Ltd operates dedicated mobile service vans across ${areaName} and all surrounding postcodes, offering same-week appointments.`,
        },
        {
          question: `How much does gutter cleaning cost in ${areaName}?`,
          answer: `Standard residential gutter cleaning in ${areaName} costs between £50 and £120 depending on property size, height, and accessibility. Fixed quotes are provided before work begins.`,
        },
        {
          question: 'Do you use ladders or vacuum systems?',
          answer: 'We use advanced high-reach vacuum systems from ground level, eliminating ladder damage to your lawns, driveways, and roofline while reaching up to 4 storeys safely.',
        },
        {
          question: 'Can you repair gutters as well as clean them?',
          answer: 'Yes. Our vans carry comprehensive stocks of brackets, union joints, sealants, and downpipe fittings to complete repairs during the same visit.',
        },
      ],
    };
  }

  // 8. EXTERIOR CLEANING / RENDER / CLADDING / DRIVEWAYS
  if (slug.includes('cladding') || slug.includes('render') || slug.includes('brickwork') || slug.includes('driveway') || slug.includes('patio') || slug.includes('pressure-wash') || slug.includes('jetwash')) {
    return {
      heroTitle: title,
      heroDescription: `Professional exterior cleaning, soft washing, and pressure washing across Birmingham and the West Midlands. Restore render, cladding, driveways, and brickwork to pristine condition. Call 07421 433910.`,
      sections: [
        {
          heading: `Professional Exterior Surface & Render Cleaning`,
          content: `Algae, lichen, atmospheric pollution, and moss can severely discolour exterior render, commercial cladding, brickwork, and block paving. WOW Gutters Ltd provides specialized soft-washing and commercial hot-water pressure washing that dissolves biological staining at the root without damaging delicate monocouche render, K-Rend, or brick mortar.`,
          bullets: [
            'Low-pressure soft-wash chemical treatments safe for K-Rend, Weber, and acrylic render',
            'Commercial hot-water rotary cleaning for driveways, patios, and block paving',
            'Algae, red streak, and black mould eradication with biocide treatments',
            'Cladding washing for industrial units, retail premises, and residential rooflines',
            'Restores bright, clean appearance and dramatically enhances kerb appeal',
            'Eco-friendly, HSE-approved cleaning solutions safe for gardens and pets',
          ],
        },
        {
          heading: `Long-Lasting Results with Biocide Protection`,
          content: `High-pressure jet washing alone merely shears off surface growth, allowing algae and moss to return within months. Our biocide sanitisation penetrates deep into porous masonry and cladding seams, killing fungal spores and keeping surfaces visibly clean for up to 24 to 36 months.`,
          bullets: [
            'Prevents rapid biological regrowth for 2 to 3 years',
            'Safe, controlled application without high-pressure surface scarring',
            'Full photographic documentation before and after treatment',
            'Fully insured with £10 million public liability coverage',
            'Free on-site patch test and fixed quotation',
            'Competitive rates across Birmingham, Solihull, and the West Midlands',
          ],
        },
      ],
      faqs: [
        {
          question: 'Is soft washing safe for modern render (K-Rend / Monocouche)?',
          answer: 'Yes. Soft washing uses low pressure and specialized biocide detergents specifically designed for delicate render, removing red and green algae without blasting away the render surface.',
        },
        {
          question: 'How long do exterior cleaning results last?',
          answer: 'With our residual biocide treatment, treated render, cladding, and paving stay free of algae and biological growth for 2 to 3 years depending on tree shade and damp exposure.',
        },
        {
          question: 'How much does exterior render or cladding cleaning cost?',
          answer: 'Pricing depends on total square meterage and access. Standard residential elevations start from £120 to £280. We provide free site surveys and fixed quotes.',
        },
        {
          question: 'Do you provide commercial cladding cleaning?',
          answer: 'Yes. We clean industrial warehouse cladding, retail fascias, and commercial facades throughout the West Midlands with full RAMS provided.',
        },
      ],
    };
  }

  // 9. GENERAL GUTTER CLEANING / SERVICES (Fallback)
  return {
    heroTitle: title,
    heroDescription: `Professional gutter cleaning, repairs, and roofline maintenance across Birmingham and the West Midlands. WOW Gutters Ltd provides ground-level vacuum cleaning, camera inspections, and free quotes. Call 07421 433910.`,
    sections: [
      {
        heading: `Comprehensive Gutter Cleaning & Maintenance`,
        content: `Clean, free-flowing gutters are vital for protecting your property from water ingress, damp walls, and roofline rot. WOW Gutters Ltd provides thorough gutter clearance using ground-level industrial vacuum systems that extract all leaves, moss, and compacted silt to the channel floor without placing ladders against your walls.`,
        bullets: [
          'Ground-level vacuum system reaching up to 4 storeys safely',
          'Complete extraction of leaves, moss, silt, and standing debris',
          'Downpipe outlet unblocking and comprehensive flow testing included',
          'Before and after HD photographic records provided with every visit',
          'Minor repairs, union joint resealing, and bracket adjustments available',
          'Fully insured with £10 million public liability cover',
        ],
      },
      {
        heading: `Why Choose WOW Gutters Ltd for Your Property`,
        content: `Our local technicians are equipped with advanced camera inspection tools and industrial vacuums, ensuring every gutter run is completely clear and structurally sound. We offer fixed pricing with no hidden charges and same-week availability across the West Midlands.`,
        bullets: [
          'Local, experienced team with hundreds of 5-star customer reviews',
          'Prevents costly water damage, internal damp, and timber decay',
          'Free 60-second online quote with same-day and next-day booking',
          'Combined gutter, roof cleaning, and uPVC washing packages available',
          'Serving residential homeowners, landlords, and commercial facilities',
          'Honest advice and transparent pricing on every visit',
        ],
      },
    ],
    faqs: [
      {
        question: 'How often should gutters be cleaned?',
        answer: 'Most UK properties should have their gutters cleaned at least once a year in late autumn. Homes under mature trees or with heavy roof moss benefit from twice-yearly clearance.',
      },
      {
        question: 'How much does professional gutter cleaning cost?',
        answer: 'Standard residential gutter cleaning costs between £50 and £120 depending on property size, height, and access. We provide fixed quotes before commencing work.',
      },
      {
        question: 'Do you check downpipes as part of the clean?',
        answer: 'Yes. Every gutter cleaning visit includes downpipe outlet clearing and flow testing to ensure rainwater drains freely to ground drains.',
      },
      {
        question: 'How do you clean gutters without ladders?',
        answer: 'We use high-reach carbon fiber vacuum systems powered by industrial suction units from ground level, eliminating ladder damage to walls and rooflines.',
      },
    ],
  };
}

function getContent(keyword: string): { heroTitle: string; heroDescription: string; sections: { heading: string; content: string; bullets: string[] }[]; faqs?: { question: string; answer: string }[] } {
  const slug = slugify(keyword);

  if (CUSTOM_KEYWORD_CONTENT[slug]) {
    return CUSTOM_KEYWORD_CONTENT[slug];
  }

  return generateSmartContent(keyword, slug);
}

export const KEYWORD_PAGES: Record<string, KeywordPage> = {};

/* Add commercial pages for all AREA_SLUGS */
for (const areaSlug of AREA_SLUGS) {
  RAW_KEYWORDS.push(`commercial-roof-cleaning-${areaSlug}`);
  RAW_KEYWORDS.push(`commercial-gutter-cleaning-${areaSlug}`);
  RAW_KEYWORDS.push(`commercial-gutter-clearing-${areaSlug}`);
}

/* Add custom unique keyword landing pages */
for (const customSlug of Object.keys(CUSTOM_KEYWORD_CONTENT)) {
  RAW_KEYWORDS.push(customSlug);
}

for (const raw of RAW_KEYWORDS) {
  const slug = slugify(raw);
  const data = getContent(raw);
  const displayName = titleCase(
    raw
      .replace(/[,.'"]/g, '')
      .replace(/\s*,\s*/g, ', ')
      .trim()
  );

  KEYWORD_PAGES[slug] = {
    slug,
    titleTag: `${displayName} | WOW Gutters Ltd`,
    metaDescription: data.heroDescription.slice(0, 160),
    heroTitle: data.heroTitle,
    heroDescription: data.heroDescription,
    sections: data.sections,
    faqs: data.faqs,
    cta: {
      title: `Book Your ${data.heroTitle.includes('Clean') ? 'Clean' : 'Service'} Today`,
      description: 'Free quotes in 60 seconds. Same-day and next-day appointments where available. Call 07421 433910 or book online.',
    },
  };
}

export function getKeywordPage(slug: string): KeywordPage | undefined {
  return KEYWORD_PAGES[slug];
}

export function getAllKeywordSlugs(): string[] {
  return Object.keys(KEYWORD_PAGES);
}
