import type { SuburbPageData } from '@/components/areas/SuburbGutterCleaningPage'

export const suburbPages: Record<string, SuburbPageData> = {
  moseley: {
    city: 'Moseley',
    heroBadge: 'Local Moseley specialists • Same-day booking',
    heroTitleLine1: 'Gutter Cleaning Moseley',
    heroTitleLine2: 'Professional Service for B13 Properties',
    whyTitle: 'Why Moseley Gutters Need Regular Professional Cleaning',
    whyParagraphs: [
      'Moseley is one of Birmingham\'s most beautiful and tree-lined suburbs — and that character comes at a cost to your gutters every autumn. The mature lime trees lining Alcester Road, the established oaks in residential gardens throughout Salisbury Road and Wake Green Road, and the ancient woodland of nearby Moseley Bog all shed significant volumes of leaves, seeds and organic debris from October through to December.',
      'Properties throughout B13 experience some of the heaviest leaf fall in Birmingham. A gutter on a Victorian terrace in St Mary\'s Row can fill completely within two to three weeks of peak leaf fall season — and the consequence of leaving it is not just overflow. Standing water in a blocked gutter freezes in winter, expanding and cracking joints. Overflow runs down the beautiful period brickwork Moseley is known for, leaving green staining and in time causing damp penetration through external walls.',
      'Moseley\'s housing stock makes this particularly important. The area is characterised by Victorian and Edwardian properties — terraces, semis and large detached homes — many with original or early-replacement cast iron and uPVC gutter systems that are vulnerable to joint failure when debris is left to accumulate. Our post-clean condition report gives you a clear picture of the state of your guttering after every visit, with honest recommendations and no pressure to spend further.',
    ],
    propertyTypesTitle: 'Gutter Cleaning for Every Moseley Property Type',
    propertyTypes: [
      { label: 'Victorian terraces (St Mary\'s Row, Woodbridge Road, Salisbury Road)', detail: 'Moseley\'s Victorian terraces are among the most characterful properties in Birmingham — and among the most challenging for conventional ladder-based cleaning. Original cast iron guttering on these properties requires careful handling; our vacuum system operates from the ground, placing nothing against your brickwork or paintwork.' },
      { label: 'Edwardian semis (Wake Green Road, Oxford Road, College Road)', detail: 'The large Edwardian semis along Wake Green Road and Oxford Road have generous gutter runs and multiple downpipes. Our 4-storey reach covers every section in a single visit, with full downpipe flushing included at no extra charge.' },
      { label: 'Large detached homes (Moseley Park area, Church Road)', detail: 'Moseley\'s larger detached properties often have complex rooflines with multiple valleys and sections. Our vacuum system handles the full length from the ground — no scaffolding, no cherry pickers, no disruption to gardens.' },
      { label: 'Converted flats and apartments', detail: 'Many of Moseley\'s larger Victorian villas have been converted to flats. We work with freeholders and managing agents, provide photographic evidence for maintenance records, and can arrange planned maintenance contracts for blocks.' },
      { label: 'Period properties near Moseley Bog', detail: 'The properties bordering Moseley Bog nature reserve experience above-average leaf and debris fall due to proximity to ancient woodland. Annual cleaning is particularly important for these homes.' },
    ],
    areasCoveredTitle: 'Areas We Cover Around Moseley',
    areasCoveredText: 'Kings Heath, Balsall Heath, Sparkhill | Stirchley, Bournville, Selly Park | Hall Green, Billesley | Nearby: Birmingham city centre, Harborne, Edgbaston',
    areaLinks: [
      { href: '/gutter-cleaning-birmingham/', label: 'Gutter cleaning Birmingham' },
      { href: '/gutter-cleaning-kings-heath/', label: 'Gutter cleaning Kings Heath' },
      { href: '/gutter-cleaning-harborne/', label: 'Gutter cleaning Harborne' },
      { href: '/gutter-cleaning-edgbaston/', label: 'Gutter cleaning Edgbaston' },
      { href: '/help/repair/', label: 'Gutter repairs' },
      { href: '/services/upvc-cleaning/', label: 'Fascia & soffit cleaning' },
    ],
    whatsappPrefix: 'Moseley',
    faqs: [
      { question: 'How much does gutter cleaning cost in Moseley?', answer: 'Prices start from £55 for a standard terraced property in Moseley. Most Victorian and Edwardian semis in B13 range from £65 to £90, and larger detached properties from £90 to £140. All prices include downpipe flushing and before & after photos. Fixed quote provided before work starts — no hidden fees.' },
      { question: 'Is there a gutter cleaning service near me in Moseley?', answer: 'Yes — WOW Gutters covers all of Moseley (B13) including properties near Moseley Park & Pool, along Alcester Road, Salisbury Road, Wake Green Road, St Mary\'s Row, Woodbridge Road and all surrounding streets. We work in Moseley regularly and can often book within 2 to 3 working days. Call 07421 433910 to check today\'s availability.' },
      { question: 'Do you clean gutters near Moseley Park and the village area?', answer: 'Yes — we regularly work throughout the Moseley village area, on properties along St Mary\'s Row and on homes backing onto Moseley Park & Pool. The park\'s mature trees mean these properties experience significant leaf fall each autumn.' },
      { question: 'Can blocked gutters cause damp in Moseley\'s Victorian properties?', answer: 'Yes — this is one of the most common problems we see in B13. Victorian and Edwardian properties have solid brick construction, and when gutters overflow against the wall the water has nowhere to go except inward. We see interior damp patches, stained brickwork and damaged window frames — all caused by blocked gutters that cost a fraction of the repair bill to maintain.' },
      { question: 'What postcodes do you cover in Moseley?', answer: 'We cover B13 in full, including B13 0, B13 8 and B13 9 sectors. Key streets include Alcester Road, Salisbury Road, Wake Green Road, Oxford Road, College Road, Church Road, St Mary\'s Row, Woodbridge Road, Woodfield Road, Prospect Road and all surrounding streets. We also cover bordering postcodes B14 (Kings Heath), B12 (Balsall Heath) and B11 (Sparkhill).' },
      { question: 'Do you offer fascia and soffit cleaning in Moseley?', answer: 'Yes — our hot purified water system restores fascias and soffits on Moseley\'s period properties to a bright, streak-free finish. Popular with homeowners preparing to sell or following a roof replacement. Particularly effective on the white-painted uPVC rooflines common on Moseley\'s Edwardian semis.' },
      { question: 'How quickly can you get to Moseley?', answer: 'We aim to offer bookings within 2 to 5 working days across Moseley. Same-day visits may be available — call 07421 433910 to check availability.' },
    ],
    reviews: [
      { initial: 'M', name: 'Mark M.', place: 'Moseley', text: 'Harley came out to sort my gutters today. Great service, friendly and professional. Pictures showed how blocked the gutters were — couldn\'t believe it! Would 100% recommend.' },
      { initial: 'N', name: 'Neil G.', place: 'Moseley', text: 'Excellent, friendly and professional service from Ian. We had persistent leaks at various points around the house — all sorted now. Highly recommend WOW Gutters.' },
      { initial: 'G', name: 'Graham B.', place: 'Kings Heath', text: 'Highly recommended. Friendly service, arrived on time and did a thorough job. The before and after photos were brilliant — you could really see the difference.' },
    ],
    postcodesTitle: 'Gutter Cleaning Across Moseley — Postcodes We Cover',
    postcodeStreetTitle: 'We cover all B13 postcodes across Moseley, including:',
    postcodeStreets: ['Alcester Road', 'Salisbury Road', 'Wake Green Road', 'Oxford Road', 'College Road', 'Church Road', 'St Mary\'s Row', 'Woodbridge Road', 'Woodfield Road', 'Prospect Road', 'Chantry Road', 'Russell Road', 'Stoney Lane', 'Billesley Lane', 'Park Hill', 'Valentine Road', 'Trafalgar Road', 'Springfield Road', 'Richmond Road'],
    postcodeFooter: 'We also cover the bordering areas of Kings Heath (B14), Balsall Heath (B12), Sparkhill (B11), Sparkbrook (B12) and Stirchley (B30).',
    bookingTitle: 'Book Your Gutter Clean in Moseley — Free Quote in 60 Seconds',
    mapTitle: 'WOW Gutters — Moseley B13 service area map',
    mapSrc: 'https://www.openstreetmap.org/export/embed.html?bbox=-1.910%2C52.435%2C-1.860%2C52.465&layer=mapnik&marker=52.4479%2C-1.8831',
    blogLocality: 'Moseley',
  },

  'weoley-castle': {
    city: 'Weoley Castle',
    heroBadge: 'Local Weoley Castle specialists • Same-day booking',
    heroTitleLine1: 'Gutter Cleaning Weoley Castle',
    heroTitleLine2: 'Professional Service for B29 Properties',
    whyTitle: 'Why Weoley Castle Gutters Need Regular Professional Cleaning',
    whyParagraphs: [
      'Weoley Castle is a residential suburb in south-west Birmingham with a rich history dating back to the 13th-century Weoley Castle fortified manor house. The area was largely developed between the 1930s and 1960s, with a mix of council estates, private semis and post-war housing. Mature garden trees throughout Barnes Hill, Somerford Road and Shenley Lane shed significant leaf fall.',
      'The area sits on elevated ground, exposed to south-westerly weather, meaning gutters fill faster with wind-blown debris. Many properties have original or early-replacement uPVC guttering now showing its age — joints fail when debris accumulates, and overflow runs down external walls causing staining and damp penetration.',
      'Weoley Castle\'s housing stock makes this particularly important. The area is characterised by a mix of post-war semis, terraces, council estates and larger detached homes — many with original or early-replacement uPVC gutter systems that are vulnerable to joint failure when debris is left to accumulate. Our post-clean condition report gives you a clear picture of the state of your guttering after every visit, with honest recommendations and no pressure to spend further.',
    ],
    propertyTypesTitle: 'Gutter Cleaning for Every Weoley Castle Property Type',
    propertyTypes: [
      { label: 'Post-war semis & terraces (Barnes Hill, Somerford Road, Beckbury Road)', detail: 'Standard uPVC gutter runs with heavy leaf and moss accumulation from mature garden trees. Our vacuum system clears all debris thoroughly with full downpipe flushing included.' },
      { label: '1930s semis (Shenley Lane, Alwold Road, Quarry Road)', detail: 'Older uPVC and cast iron systems requiring careful handling. We clean from ground level placing nothing against your brickwork.' },
      { label: 'Council estate properties (Weoley Castle Estate, Farwood Road area)', detail: 'Dense housing stock where gutters block quickly from leaf fall and moss. Efficient service with no disruption to neighbours.' },
      { label: 'Detached homes (Gregory Avenue, Bartley Green border)', detail: 'Larger properties with longer gutter runs and complex rooflines. Our 4-storey reach covers all sections.' },
      { label: 'Period properties near the Castle ruins', detail: 'Characterful homes near the historic Weoley Castle site with mixed gutter systems. We take extra care with fragile or aged guttering.' },
    ],
    areasCoveredTitle: 'Areas We Cover Around Weoley Castle',
    areasCoveredText: 'Selly Oak, Harborne, Bartley Green | Northfield, Kings Norton, Shenley Fields | Nearby: Birmingham city centre, Edgbaston, Quinton',
    areaLinks: [
      { href: '/gutter-cleaning-birmingham/', label: 'Gutter cleaning Birmingham' },
      { href: '/gutter-cleaning-selly-oak/', label: 'Gutter cleaning Selly Oak' },
      { href: '/gutter-cleaning-harborne/', label: 'Gutter cleaning Harborne' },
      { href: '/gutter-cleaning-edgbaston/', label: 'Gutter cleaning Edgbaston' },
      { href: '/help/repair/', label: 'Gutter repairs' },
      { href: '/services/upvc-cleaning/', label: 'Fascia & soffit cleaning' },
    ],
    whatsappPrefix: 'Weoley Castle',
    faqs: [
      { question: 'How much does gutter cleaning cost in Weoley Castle?', answer: 'Prices start from £50 for a standard terraced property in Weoley Castle. Most semi-detached properties in B29 range from £60 to £80, and larger detached properties from £80 to £120. All prices include downpipe flushing and before & after photos. Fixed quote provided before work starts — no hidden fees.' },
      { question: 'Is there a gutter cleaning service near me in Weoley Castle?', answer: 'Yes — WOW Gutters covers all of Weoley Castle (B29) including properties along Barnes Hill, Weoley Castle Road, Somerford Road, Shenley Lane and all surrounding streets. We work in Weoley Castle regularly and can often book within 2 to 3 working days. Call 07421 433910 to check today\'s availability.' },
      { question: 'Do you cover the Weoley Castle Square shopping area?', answer: 'Yes — we regularly work on properties throughout Weoley Castle including homes near Weoley Castle Square, around the Castle ruins on Alwold Road, and all streets between Somerford Road and Shenley Lane.' },
      { question: 'Can blocked gutters cause damp in Weoley Castle\'s older properties?', answer: 'Yes — many properties in Weoley Castle date from the 1930s through to the 1960s, and their solid brick construction is vulnerable to damp when gutters overflow. Water running down external walls can penetrate brickwork, causing interior damp patches, stained walls and damaged window frames. Annual gutter cleaning prevents all of this at a fraction of the repair cost.' },
      { question: 'What postcodes do you cover in Weoley Castle?', answer: 'We cover B29 in full, including B29 5 and B29 6 sectors. Key streets include Barnes Hill, Weoley Castle Road, Somerford Road, Shenley Lane, Alwold Road, Beckbury Road, Quarry Road, Gregory Avenue, Farwood Road and all surrounding streets. We also cover bordering postcodes B31 (Northfield), B32 (Bartley Green) and B17 (Harborne).' },
      { question: 'Do you offer fascia and soffit cleaning in Weoley Castle?', answer: 'Yes — our hot purified water system restores fascias and soffits on Weoley Castle properties to a bright, streak-free finish. Particularly effective on the uPVC rooflines common on post-war homes throughout the area.' },
      { question: 'How quickly can you get to Weoley Castle?', answer: 'We aim to offer bookings within 2 to 5 working days across Weoley Castle. Same-day visits may be available — call 07421 433910 to check availability.' },
    ],
    reviews: [
      { initial: 'M', name: 'Mark M.', place: 'Weoley Castle', text: 'Harley came out to sort my gutters today. Great service, friendly and professional. Pictures showed how blocked the gutters were — couldn\'t believe it! Would 100% recommend.' },
      { initial: 'C', name: 'Carol T.', place: 'Weoley Castle', text: 'Excellent, friendly and professional service from Ian. We had persistent leaks at various points around the house — all sorted now. Highly recommend WOW Gutters.' },
      { initial: 'D', name: 'David R.', place: 'Selly Oak', text: 'Highly recommended. Friendly service, arrived on time and did a thorough job. The before and after photos were brilliant — you could really see the difference.' },
    ],
    postcodesTitle: 'Gutter Cleaning Across Weoley Castle — Postcodes We Cover',
    postcodeStreetTitle: 'We cover all B29 postcodes across Weoley Castle, including:',
    postcodeStreets: ['Barnes Hill', 'Weoley Castle Road', 'Somerford Road', 'Shenley Lane', 'Alwold Road', 'Beckbury Road', 'Quarry Road', 'Gregory Avenue', 'Farwood Road', 'Green Meadow Road', 'Marston Road', 'Anwold Road', 'Dawlish Road', 'Hubert Road', 'Oak Tree Lane', 'Chapel Lane', 'New Fosse Way', 'Shenley Fields Drive'],
    postcodeFooter: 'We also cover the bordering areas of Northfield (B31), Bartley Green (B32), Harborne (B17) and Selly Oak (B29).',
    bookingTitle: 'Book Your Gutter Clean in Weoley Castle — Free Quote in 60 Seconds',
    mapTitle: 'WOW Gutters — Weoley Castle B29 service area map',
    mapSrc: 'https://www.openstreetmap.org/export/embed.html?bbox=-1.985%2C52.425%2C-1.940%2C52.455&layer=mapnik&marker=52.4370%2C-1.9700',
    blogLocality: 'Weoley Castle',
  },

  'west-heath': {
    city: 'West Heath',
    heroBadge: 'Local West Heath specialists • Same-day booking',
    heroTitleLine1: 'Gutter Cleaning West Heath',
    heroTitleLine2: 'Professional Service for B31 Properties',
    whyTitle: 'Why West Heath Gutters Need Regular Professional Cleaning',
    whyParagraphs: [
      'West Heath is a residential area of south Birmingham lying between Northfield and Longbridge, close to the Rea Valley. The area was largely developed in the interwar and post-war periods, with significant council estate development around Turves Green and Fairfax Road during the 1960s. Mature trees throughout West Heath Road, Turves Green and the residential streets create heavy leaf fall each autumn.',
      'The area sits on the elevated ridge above the River Rea, catching wind-driven debris and rainfall. Many properties have their original uPVC guttering — now 40-60 years old — which is prone to joint failure when debris accumulates. Overflow runs down external walls, causing damp in solid brick construction. Annual cleaning prevents expensive repair bills.',
      'West Heath\'s housing stock makes regular maintenance particularly important. The area is characterised by interwar and post-war properties — semis, bungalows and council estate homes — many with original or early-replacement uPVC gutter systems that are vulnerable to joint failure when debris is left to accumulate. Our post-clean condition report gives you a clear picture of the state of your guttering after every visit, with honest recommendations and no pressure to spend further.',
    ],
    propertyTypesTitle: 'Gutter Cleaning for Every West Heath Property Type',
    propertyTypes: [
      { label: 'Interwar semis (West Heath Road, Longbridge Lane)', detail: 'Classic 1930s semis with uPVC gutter runs. Leaf and moss build-up cleared thoroughly with downpipe flush included. These properties are common throughout West Heath and benefit from annual cleaning to keep the original uPVC systems in good working order.' },
      { label: 'Turves Green estate properties (Fairfax Road, Turves Green area)', detail: '1960s council estate homes with tower blocks, maisonettes and semis. Dense housing where blockages spread quickly. Our vacuum system handles all heights up to 4 storeys, making quick work of the varied property types across the estate.' },
      { label: 'Post-war semis (West Heath village area, Cofton Hackett border)', detail: 'Standard uPVC systems with mature garden tree coverage. Annual clean keeps everything flowing properly. These properties on the southern edge of West Heath benefit from regular maintenance given their proximity to the open countryside near Cofton Hackett.' },
      { label: 'Northfield border properties', detail: 'Mix of terraced and semi-detached homes along the boundary between West Heath and Northfield. Same professional service, same pricing, same guarantee. We cover both sides of the border without distinction.' },
      { label: 'Bungalows and retirement properties', detail: 'Popular in the West Heath area. Quick, affordable clean with same professional standard. Our ground-level vacuum system is ideal for bungalows — no ladders needed, no disturbance to residents, and a faster clean time at a lower price point.' },
    ],
    areasCoveredTitle: 'Areas We Cover Around West Heath',
    areasCoveredText: 'Northfield, Longbridge, Kings Norton | Cofton Hackett, Turves Green, Rubery | Nearby: Birmingham city centre, Selly Oak, Bournville',
    areaLinks: [
      { href: '/gutter-cleaning-birmingham/', label: 'Gutter cleaning Birmingham' },
      { href: '/gutter-cleaning-kings-norton/', label: 'Gutter cleaning Kings Norton' },
      { href: '/gutter-cleaning-northfield/', label: 'Gutter cleaning Northfield' },
      { href: '/help/repair/', label: 'Gutter repairs' },
      { href: '/services/upvc-cleaning/', label: 'Fascia & soffit cleaning' },
    ],
    whatsappPrefix: 'West Heath',
    faqs: [
      { question: 'How much does gutter cleaning cost in West Heath?', answer: 'Prices start from £50 for a standard terraced property in West Heath. Most interwar and post-war semis in B31 range from £60 to £85, and larger detached properties from £85 to £115. All prices include downpipe flushing and before & after photos. Fixed quote provided before work starts — no hidden fees.' },
      { question: 'Is there a gutter cleaning service near me in West Heath?', answer: 'Yes — WOW Gutters covers all of West Heath (B31) including properties along West Heath Road, Turves Green, Fairfax Road, Longbridge Lane and all surrounding streets in the Northfield and Longbridge border area. We work in West Heath regularly and can often book within 2 to 3 working days. Call 07421 433910 to check today\'s availability.' },
      { question: 'Do you clean gutters in the Turves Green area of West Heath?', answer: 'Yes — we regularly work throughout the Turves Green estate area, including Fairfax Road, Turves Green, and the surrounding maisonettes, tower blocks and semis. Our vacuum system handles all heights up to 4 storeys, so we can clean every property on the estate without ladders or scaffolding.' },
      { question: 'Can blocked gutters cause damp in West Heath\'s post-war homes?', answer: 'Yes — this is one of the most common problems we see in B31. West Heath\'s post-war homes have solid brick construction, and when gutters overflow against the wall the water has nowhere to go except inward. We see interior damp patches, stained brickwork and damaged window frames — all caused by blocked gutters that cost a fraction of the repair bill to maintain.' },
      { question: 'What postcodes do you cover in West Heath?', answer: 'We cover B31 in full, including B31 3 and B31 4 sectors. Key streets include West Heath Road, Turves Green, Fairfax Road, Longbridge Lane, Westhaven Drive, Cromwell Lane, Senneleys Park Road, Woodcock Lane, Roundlea Road, Hillwood Road, Genners Lane, Long Nuke Road, Moors Lane and all surrounding streets. We also cover bordering postcodes B45 (Northfield, Rubery) and B38 (Kings Norton).' },
      { question: 'Do you offer fascia and soffit cleaning in West Heath?', answer: 'Yes — our hot purified water system restores fascias and soffits on West Heath\'s interwar and post-war properties to a bright, streak-free finish. Popular with homeowners preparing to sell or following a roof replacement. Particularly effective on the uPVC rooflines common on West Heath\'s 1930s semis.' },
      { question: 'How quickly can you get to West Heath?', answer: 'We aim to offer bookings within 2 to 5 working days across West Heath. Same-day visits may be available — call 07421 433910 to check availability.' },
    ],
    reviews: [
      { initial: 'P', name: 'Paul T.', place: 'West Heath', text: 'Ian came out to do my gutters today. Great price, really thorough work, and the photos showed exactly what was going on up there. Will be booking annually from now on.' },
      { initial: 'S', name: 'Susan W.', place: 'West Heath', text: 'Brilliant service from start to finish. Quick quote over the phone, arrived on time, and the gutters have never been this clean. No mess left in the garden either. Highly recommend.' },
      { initial: 'D', name: 'David R.', place: 'Northfield', text: 'Lived here 20 years and never seen the gutters this clean. The before photos were eye-opening — so much junk up there. Downpipes flowing freely now. Fair price, friendly lads.' },
    ],
    postcodesTitle: 'Gutter Cleaning Across West Heath — Postcodes We Cover',
    postcodeStreetTitle: 'We cover all B31 postcodes across West Heath, including:',
    postcodeStreets: ['West Heath Road', 'Turves Green', 'Fairfax Road', 'Longbridge Lane', 'Westhaven Drive', 'Cromwell Lane', 'Senneleys Park Road', 'Woodcock Lane', 'Roundlea Road', 'Hillwood Road', 'Genners Lane', 'Long Nuke Road', 'Moors Lane', 'Far Wood Road', 'Corwen Croft', 'Bartley Drive', 'Bridgeburn Road'],
    postcodeFooter: 'We also cover the bordering areas of Northfield and Rubery (B45), and Kings Norton (B38).',
    bookingTitle: 'Book Your Gutter Clean in West Heath — Free Quote in 60 Seconds',
    mapTitle: 'WOW Gutters — West Heath B31 service area map',
    mapSrc: 'https://www.openstreetmap.org/export/embed.html?bbox=-1.985%2C52.390%2C-1.930%2C52.420&layer=mapnik&marker=52.4010%2C-1.9620',
    blogLocality: 'West Heath',
  },

  witton: {
    city: 'Witton',
    heroBadge: 'Local Witton specialists • Same-day booking',
    heroTitleLine1: 'Gutter Cleaning Witton',
    heroTitleLine2: 'Professional Service for B6 Properties',
    whyTitle: 'Why Witton Gutters Need Regular Professional Cleaning',
    whyParagraphs: [
      'Witton is a densely built inner-city area of Birmingham, lying between Aston and Perry Barr and best known as the home of Villa Park, Aston Villa Football Club. The area is characterised by dense Victorian terraced streets built during Birmingham\'s industrial expansion, alongside significant post-war and 1960s housing developments.',
      'Mature street trees along Witton Road and the residential streets shed leaves heavily each autumn, and the area\'s consistent urban rainfall — combined with aging gutter systems on many Victorian properties — means blockages develop quickly. Many of Witton\'s Victorian terraces have original or early-replacement cast iron guttering that requires careful handling.',
      'Overflow from blocked gutters runs down solid brick walls, causing damp penetration, stained brickwork and damaged window frames. With the area\'s high proportion of rental properties and HMOs, gutter maintenance is often overlooked between tenancies, leading to expensive damp remediation that a simple annual clean would have prevented.',
    ],
    propertyTypesTitle: 'Gutter Cleaning for Every Witton Property Type',
    propertyTypes: [
      { label: 'Victorian terraces (Witton Road, Trinity Road, Station Road area)', detail: 'Dense terraced rows with aging cast iron and uPVC gutter systems. We clear carefully from ground level and flag any repairs needed. No side access required. Many of Witton\'s Victorian properties have original or early-replacement cast iron guttering that requires careful handling — our vacuum system operates entirely from ground level, placing nothing against your brickwork.' },
      { label: 'Post-war semis (Mansfield Road area, Perry Barr border)', detail: 'Standard uPVC runs on these 1960s and 1970s properties. Leaf and moss build-up cleared thoroughly with full downpipe flush included. Our 4-storey reach covers every section in a single visit, and we photograph the results as standard.' },
      { label: 'Villa Park area properties', detail: 'Homes near the stadium experience additional debris from match-day traffic and street cleaning, as well as heavy leaf fall from mature street trees. An annual clean is strongly recommended for these properties to prevent the rapid build-up that occurs during autumn and winter.' },
      { label: 'Converted flats and HMOs', detail: 'Landlords across Witton use WOW Gutters for annual maintenance on rental portfolios. We provide photo evidence for every visit, making it easy to demonstrate compliance and keep maintenance records organised across multiple properties.' },
      { label: 'Commercial properties (Witton Road corridor)', detail: 'Shops, takeaways and businesses with flats above along Witton Road and the Six Ways area. Planned maintenance contracts available. We work around business hours and provide before & after photo reports for your records.' },
    ],
    areasCoveredTitle: 'Areas We Cover Around Witton',
    areasCoveredText: 'Aston, Perry Barr, Erdington | Nechells, Aston University area, Birchfield | Nearby: Birmingham city centre, Handsworth, Lozells',
    areaLinks: [
      { href: '/gutter-cleaning-birmingham/', label: 'Gutter cleaning Birmingham' },
      { href: '/gutter-cleaning-aston/', label: 'Gutter cleaning Aston' },
      { href: '/gutter-cleaning-erdington/', label: 'Gutter cleaning Erdington' },
      { href: '/help/repair/', label: 'Gutter repairs' },
      { href: '/services/upvc-cleaning/', label: 'Fascia & soffit cleaning' },
    ],
    whatsappPrefix: 'Witton',
    faqs: [
      { question: 'How much does gutter cleaning cost in Witton?', answer: 'Prices start from £45 for a standard terraced property in Witton. Most Victorian semis and post-war homes in B6 range from £55 to £80, and larger detached or commercial properties from £80 to £110. All prices include downpipe flushing and before & after photos. Fixed quote provided before work starts — no hidden fees.' },
      { question: 'Is there a gutter cleaning service near me in Witton?', answer: 'Yes — WOW Gutters covers all of Witton (B6) including properties near Villa Park, along Witton Road, Trinity Road, Station Road, Mansfield Road and all surrounding streets. We work in Witton regularly and can often book within 2 to 3 working days. Call 07421 433910 to check today\'s availability.' },
      { question: 'Do you clean gutters near Villa Park and the surrounding area?', answer: 'Yes — we regularly work throughout the Villa Park area and the residential streets surrounding the stadium. Properties near Villa Park experience additional debris from match-day traffic and street cleaning as well as leaf fall from mature trees along the residential streets. An annual clean is particularly recommended for these homes.' },
      { question: 'Can blocked gutters cause damp in Witton\'s Victorian properties?', answer: 'Yes — this is one of the most common problems we see in B6. Witton\'s Victorian terraces have solid brick construction, and when gutters overflow against the wall the water has nowhere to go except inward. We see interior damp patches, stained brickwork and damaged window frames — all caused by blocked gutters that cost a fraction of the repair bill to maintain.' },
      { question: 'What postcodes do you cover in Witton?', answer: 'We cover B6 in full, including B6 4, B6 5, B6 6 and B6 7 sectors. Key streets include Witton Road, Trinity Road, Station Road, Mansfield Road, Church Road, Park Road, Queen Street, Albert Road, Victoria Road, Portland Road, Kings Road, School Lane, College Road, Reservoir Road, Six Ways, Aston Lane, Birchfield Road and Lichfield Road. We also cover bordering postcodes B42 (Perry Barr), B24 (Erdington) and B19 (Aston/Lozells).' },
      { question: 'Do you offer fascia and soffit cleaning in Witton?', answer: 'Yes — our hot purified water system restores fascias and soffits on Witton\'s properties to a bright, streak-free finish. Popular with landlords preparing properties for new tenants and homeowners following a roof replacement. Particularly effective on the uPVC rooflines common across Witton\'s post-war housing stock.' },
      { question: 'How quickly can you get to Witton?', answer: 'We aim to offer bookings within 2 to 5 working days across Witton. Same-day visits may be available — call 07421 433910 to check availability.' },
    ],
    reviews: [
      { initial: 'P', name: 'Paul D.', place: 'Witton', text: 'Great service from Ian. Gutters were completely blocked with leaves and moss — we had water running down the walls. All cleared out, photos sent, no mess left. Will definitely book again next year.' },
      { initial: 'S', name: 'Sharon T.', place: 'Perry Barr', text: 'Came out to sort the gutters on our rental property in Witton. Very professional, sent before and after photos which the landlord loved. Reasonable price too. Would highly recommend.' },
      { initial: 'J', name: 'James R.', place: 'Aston', text: 'Harley did a brilliant job on our Victorian terrace. No ladders against the house, everything cleaned from the ground. You could see the difference in the photos. Fair price and friendly service.' },
    ],
    postcodesTitle: 'Gutter Cleaning Across Witton — Postcodes We Cover',
    postcodeStreetTitle: 'We cover all B6 postcodes across Witton, including:',
    postcodeStreets: ['Witton Road', 'Trinity Road', 'Station Road', 'Mansfield Road', 'Church Road', 'Park Road', 'Queen Street', 'Albert Road', 'Victoria Road', 'Portland Road', 'Kings Road', 'School Lane', 'College Road', 'Reservoir Road', 'Six Ways', 'Aston Lane', 'Birchfield Road', 'Lichfield Road'],
    postcodeFooter: 'We also cover the bordering areas of Aston (B6), Perry Barr (B42), Erdington (B24), Nechells (B7) and Lozells (B19).',
    bookingTitle: 'Book Your Gutter Clean in Witton — Free Quote in 60 Seconds',
    mapTitle: 'WOW Gutters — Witton B6 service area map',
    mapSrc: 'https://www.openstreetmap.org/export/embed.html?bbox=-1.910%2C52.495%2C-1.860%2C52.520&layer=mapnik&marker=52.5050%2C-1.8850',
    blogLocality: 'Witton',
  },

  'wylde-green': {
    city: 'Wylde Green',
    heroBadge: 'Local Wylde Green specialists • Same-day booking',
    heroTitleLine1: 'Gutter Cleaning Wylde Green',
    heroTitleLine2: 'Professional Service for B73 Properties',
    whyTitle: 'Why Wylde Green Gutters Need Regular Professional Cleaning',
    whyParagraphs: [
      'Wylde Green is a desirable residential area of Sutton Coldfield, situated close to Sutton Park — one of Europe\'s largest urban parks. The area is known for its attractive Edwardian and early 20th-century semis and detached homes, particularly along Birmingham Road, Green Lane and the surrounding residential streets.',
      'Proximity to Sutton Park means properties here experience heavy leaf fall from the park\'s ancient woodland and heathland, as well as from established garden trees throughout the area. Wylde Green\'s elevated position means it catches wind-driven debris and rainfall. A gutter on an Edwardian semi in Birmingham Road can fill completely within two to three weeks of peak leaf fall season — and the consequence of leaving it is not just overflow. Standing water in a blocked gutter freezes in winter, expanding and cracking joints.',
      'Many of the area\'s Edwardian and 1930s properties have original cast iron or early uPVC guttering that requires careful maintenance. The high value of properties in the B73 area means that preventing water damage through regular gutter cleaning is a particularly cost-effective investment — damp repairs on period properties can run into thousands. Our post-clean condition report gives you a clear picture of the state of your guttering after every visit, with honest recommendations and no pressure to spend further.',
    ],
    propertyTypesTitle: 'Gutter Cleaning for Every Wylde Green Property Type',
    propertyTypes: [
      { label: 'Edwardian semis (Birmingham Road, Green Lane, Walmley Road area)', detail: 'Characterful period properties with longer gutter runs and mature garden trees. Heavy leaf fall, full downpipe flush and condition report included. Our vacuum system handles original cast iron guttering with care — no ladders leaning against your brickwork.' },
      { label: '1930s detached homes (Wylde Green Road, Chester Road area)', detail: 'Larger properties with complex rooflines and multiple gutter sections. Our 4-storey reach covers all areas including over garages and extensions in a single visit, with full downpipe flushing included at no extra charge.' },
      { label: 'Modern executive homes (Boldmere border, Four Oaks direction)', detail: 'Newer properties with standard uPVC guttering. Annual clean maintains warranty condition and prevents moss build-up. Our vacuum system handles the full length from the ground — no ladders, no disruption.' },
      { label: 'Sutton Coldfield town centre border properties', detail: 'Mix of period and modern homes bordering Sutton Coldfield town centre. Same professional service, same guarantee. We provide photographic evidence for homeowners and landlords alike.' },
      { label: 'Flats and apartment blocks', detail: 'Low-rise blocks near Chester Road station. We work with freeholders and managing agents, provide photographic evidence for maintenance records, and can arrange planned maintenance contracts for blocks. Our vacuum system reaches all sections safely from the ground.' },
    ],
    areasCoveredTitle: 'Areas We Cover Around Wylde Green',
    areasCoveredText: 'Sutton Coldfield, Boldmere, Four Oaks | Erdington, New Oscott, Mere Green | Nearby: Birmingham city centre, Streetly, Walmley',
    areaLinks: [
      { href: '/gutter-cleaning-sutton-coldfield/', label: 'Gutter cleaning Sutton Coldfield' },
      { href: '/gutter-cleaning-birmingham/', label: 'Gutter cleaning Birmingham' },
      { href: '/gutter-cleaning-four-oaks/', label: 'Gutter cleaning Four Oaks' },
      { href: '/gutter-cleaning-erdington/', label: 'Gutter cleaning Erdington' },
      { href: '/help/repair/', label: 'Gutter repairs' },
      { href: '/services/upvc-cleaning/', label: 'Fascia & soffit cleaning' },
    ],
    whatsappPrefix: 'Wylde Green',
    faqs: [
      { question: 'How much does gutter cleaning cost in Wylde Green?', answer: 'Prices start from £60 for a standard property in Wylde Green. Most Edwardian and 1930s semis in B73 range from £70 to £100, and larger detached properties from £100 to £150. All prices include downpipe flushing and before & after photos. Fixed quote provided before work starts — no hidden fees.' },
      { question: 'Is there a gutter cleaning service near me in Sutton Coldfield?', answer: 'Yes — WOW Gutters covers all of Wylde Green and the wider Sutton Coldfield area (B73) including properties near Sutton Park, along Birmingham Road, Green Lane, Walmley Road, Chester Road and all surrounding streets. We work in Wylde Green regularly and can often book within 2 to 3 working days. Call 07421 433910 to check today\'s availability.' },
      { question: 'Do you clean gutters near Sutton Park?', answer: 'Yes — we regularly work throughout Wylde Green and the Sutton Coldfield area, on properties backing onto or close to Sutton Park. The park\'s ancient woodland and heathland mean these properties experience the heaviest leaf fall in the Birmingham area each autumn.' },
      { question: 'Can blocked gutters cause damp in Wylde Green\'s Edwardian properties?', answer: 'Yes — this is one of the most common problems we see in B73. Edwardian and 1930s properties have solid brick construction, and when gutters overflow against the wall the water has nowhere to go except inward. We see interior damp patches, stained brickwork and damaged window frames — all caused by blocked gutters that cost a fraction of the repair bill to maintain.' },
      { question: 'What postcodes do you cover in Wylde Green?', answer: 'We cover B73 in full, including B73 5, B73 6 and B73 9 sectors. Key streets include Birmingham Road, Green Lane, Walmley Road, Chester Road, Wylde Green Road, Kings Road, Jockey Road, Foley Road, Monmouth Drive, Marchmount Road, Hawthorn Road, Hollington Road, Sutton Road, Ebrook Road, Reddicap Hill, Thornhill Road, Belwell Lane, Lindridge Road, Penns Lane and all surrounding streets.' },
      { question: 'Do you offer fascia and soffit cleaning in Wylde Green?', answer: 'Yes — our hot purified water system restores fascias and soffits on Wylde Green\'s period properties to a bright, streak-free finish. Popular with homeowners preparing to sell or following a roof replacement. Particularly effective on the white-painted uPVC rooflines common on Wylde Green\'s Edwardian and 1930s semis.' },
      { question: 'How quickly can you get to Wylde Green?', answer: 'We aim to offer bookings within 2 to 5 working days across Wylde Green and Sutton Coldfield. Same-day visits may be available — call 07421 433910 to check availability.' },
    ],
    reviews: [
      { initial: 'J', name: 'Jason W.', place: 'Wylde Green', text: 'Ian came out to do the gutters on our Edwardian semi on Birmingham Road. Incredible difference — gutters were completely blocked and now they\'re spotless. The before and after photos were really impressive. Highly recommended.' },
      { initial: 'L', name: 'Linda P.', place: 'Sutton Coldfield', text: 'Great service from WOW Gutters. They cleaned the gutters on our 1930s detached in Wylde Green and even sorted a downpipe that had been blocked for years. Friendly, professional and excellent value.' },
      { initial: 'R', name: 'Richard M.', place: 'Boldmere', text: 'Couldn\'t be happier with the service. Came on time, did a thorough job and the photos showed just how bad the gutters were. No mess left in the garden. Will definitely use again next year.' },
    ],
    postcodesTitle: 'Gutter Cleaning Across Wylde Green — Postcodes We Cover',
    postcodeStreetTitle: 'We cover all B73 postcodes across Wylde Green, including:',
    postcodeStreets: ['Birmingham Road', 'Green Lane', 'Walmley Road', 'Chester Road', 'Wylde Green Road', 'Kings Road', 'Jockey Road', 'Foley Road', 'Monmouth Drive', 'Marchmount Road', 'Hawthorn Road', 'Hollington Road', 'Sutton Road', 'Ebrook Road', 'Reddicap Hill', 'Thornhill Road', 'Belwell Lane', 'Lindridge Road', 'Penns Lane'],
    postcodeFooter: 'We also cover the bordering areas of Sutton Coldfield (B72, B74), Boldmere (B73), Four Oaks (B74), Erdington (B23, B24), New Oscott (B73) and Mere Green (B75).',
    bookingTitle: 'Book Your Gutter Clean in Wylde Green — Free Quote in 60 Seconds',
    mapTitle: 'WOW Gutters — Wylde Green B73 service area map',
    mapSrc: 'https://www.openstreetmap.org/export/embed.html?bbox=-1.850%2C52.525%2C-1.810%2C52.555&layer=mapnik&marker=52.5370%2C-1.8310',
    blogLocality: 'Wylde Green',
  },
}
